// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 全局设置上下文覆盖的 Section（闭合集合；第一版只有 `reading`）。
 */
export type AgentSettingsSectionDto = "reading";
