// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourcePreferenceProposalDto } from "./AgentResourcePreferenceProposalDto";
import type { AgentSettingChangeReceiptDto } from "./AgentSettingChangeReceiptDto";

export type AgentResourcePreferenceProposalGetResultDto = { proposal: AgentResourcePreferenceProposalDto, receipt: AgentSettingChangeReceiptDto | null, };
