// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTraceEventDto } from "./AgentTraceEventDto";

/**
 * Agent 轨迹读取结果。事件上限由 Application collector 固定保证。
 */
export type AgentTraceGetResultDto = { schemaVersion: 1, sessionId: string, events: Array<AgentTraceEventDto>, };
