// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentTraceEventKindDto } from "./AgentTraceEventKindDto";

/**
 * 脱敏轨迹事件。context 只保留可重新核对的 id/hash。
 */
export type AgentTraceEventDto = { sessionId: string, requestId: string, contextId: string, contextHash: string, sequence: number, kind: AgentTraceEventKindDto, durationMs: number | null, occurredAt: string, };
