// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingChangeReceiptDto } from "./AgentSettingChangeReceiptDto";
import type { AgentSettingsProposalDto } from "./AgentSettingsProposalDto";

/**
 * 读取结果：提案 + 可能存在的回执（未应用时 `receipt` 为 null）。
 */
export type AgentSettingsProposalGetResultDto = { proposal: AgentSettingsProposalDto, receipt: AgentSettingChangeReceiptDto | null, };
