// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingChangeDto } from "./AgentSettingChangeDto";
import type { AgentSettingsProposalStatusDto } from "./AgentSettingsProposalStatusDto";

/**
 * 回执投影：只暴露「改了什么、结果如何」，不暴露 token 或任意 JSON 结构。
 */
export type AgentSettingChangeReceiptDto = { schemaVersion: 1, receiptId: string, proposalId: string, 
/**
 * 与提案 digest 同源；UI 用它核对回执确实对应自己批准的那一份。
 */
proposalDigest: string, 
/**
 * `applied` / `rejected` / `expired` / `pending`（未应用时为 pending）。
 */
status: AgentSettingsProposalStatusDto, 
/**
 * 应用后的 authoritative revision；`null` 表示没有写出新版本。
 */
appliedRevision: string | null, changed: boolean, changes: Array<AgentSettingChangeDto>, appliedAt: string, };
