// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条提案内的单项改动（从提案载荷与 authoritative 当前值推导，不由前端计算）。
 */
export type AgentSettingChangeDto = { 
/**
 * 稳定设置项 id（例如 `reading.fontSize`）。
 */
key: string, 
/**
 * 改动前的档位（Wire 枚举值字符串）。
 */
before: string, 
/**
 * 改动后的档位（Wire 枚举值字符串）。
 */
after: string, };
