// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBrokerStatusDto } from "./AgentBrokerStatusDto";

/**
 * 外部 Agent Broker 状态投影。端点只在 listening 时出现；reason 只携带稳定、可展示的
 * fail-closed 文案，不携带路径、堆栈、凭据或原始系统错误。
 */
export type AgentBrokerStatusResultDto = { schemaVersion: 1, status: AgentBrokerStatusDto, endpoint: string | null, reason: string | null, };
