// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提案状态（闭合集合）。
 */
export type AgentSettingsProposalStatusDto = "pending" | "applied" | "rejected" | "expired";
