// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 读取指定 Agent 会话轨迹的请求。
 */
export type AgentTraceGetRequest = { sessionId: string, };
