// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentLibraryCategoryCountDto } from "./AgentLibraryCategoryCountDto";
import type { AgentLibraryRecentItemDto } from "./AgentLibraryRecentItemDto";
import type { AgentLibrarySummaryCountsDto } from "./AgentLibrarySummaryCountsDto";

export type AgentLibrarySummaryDto = { schemaVersion: 1, counts: AgentLibrarySummaryCountsDto, categories: Array<AgentLibraryCategoryCountDto>, recent: Array<AgentLibraryRecentItemDto>, truncated: boolean, };
