// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 设置来源层（Agent 只读投影）。
 */
export type AgentSettingSourceLayerDto = "default" | "global" | "edition" | "media_item";
