// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingsProposalDto } from "./AgentSettingsProposalDto";

/**
 * 拒绝结果：拒绝后的提案投影（零写入）。
 */
export type AgentSettingsProposalRejectResultDto = { proposal: AgentSettingsProposalDto, };
