// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingChangeDto } from "./AgentSettingChangeDto";
import type { AgentSettingsProposalStatusDto } from "./AgentSettingsProposalStatusDto";
import type { AgentSettingsSubjectDto } from "./AgentSettingsSubjectDto";

/**
 * Agent 设置提案投影。
 *
 * `digest` 是 Rust 生成的 canonical digest（64 位小写十六进制）；UI 必须原样
 * 回传它，不得自行计算领域 digest。这里**没有** Approval Token 字段。
 */
export type AgentSettingsProposalDto = { schemaVersion: 1, proposalId: string, status: AgentSettingsProposalStatusDto, subject: AgentSettingsSubjectDto, targetLabel: string, baseRevision: string | null, digest: string, createdAt: string, expiresAt: string, changes: Array<AgentSettingChangeDto>, };
