// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 批准请求：只有提案 ID 与**UI 显示的那份 canonical digest**。
 */
export type AgentSettingsProposalApproveRequest = { proposalId: string, expectedDigest: string, };
