// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourcePreferencePatchDto } from "./AgentResourcePreferencePatchDto";
import type { AgentResourcePreferenceScopeDto } from "./AgentResourcePreferenceScopeDto";

export type AgentResourcePreferenceProposalCreateRequest = { sessionId: string, requestId: string, targetScope: AgentResourcePreferenceScopeDto, editionId: string, mediaItemId: string | null, contextId: string, contextHash: string, baseRevision: string | null, patch: AgentResourcePreferencePatchDto, };
