// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourcePreferenceScopeDto } from "./AgentResourcePreferenceScopeDto";
import type { PreferenceComicPatchDto } from "./PreferenceComicPatchDto";
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";

export type AgentResourcePreferenceSnapshotDto = { schemaVersion: 1, contextId: string, contextHash: string, targetScope: AgentResourcePreferenceScopeDto, editionId: string, mediaItemId: string | null, revision: string | null, reading: PreferenceReadingPatchDto | null, comic: PreferenceComicPatchDto | null, };
