// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilityManifestDto } from "./AgentCapabilityManifestDto";
import type { AgentSettingsReadingSnapshotDto } from "./AgentSettingsReadingSnapshotDto";
import type { AgentSettingsSubjectDto } from "./AgentSettingsSubjectDto";

/**
 * `agent_settings_context_get` 响应：读取边界（只读，无 secret/路径/正文）。
 */
export type AgentSettingsContextDto = { schemaVersion: 1, 
/**
 * 服务端派生的设置上下文身份（64 位小写十六进制 context hash 的派生 UUID）。
 */
contextId: string, 
/**
 * canonical 设置上下文载荷的 SHA-256；提案创建必须回传它。
 */
contextHash: string, subject: AgentSettingsSubjectDto, 
/**
 * authoritative 设置 revision；`null` 表示该分区从未保存过。
 */
revision: string | null, reading: AgentSettingsReadingSnapshotDto, capabilities: AgentCapabilityManifestDto, };
