// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";

/**
 * 创建设置提案的请求（闭合 typed DTO）。
 *
 * `contextId` / `contextHash` / `baseRevision` 都必须来自最近一次
 * `agent_settings_context_get`：服务端会重新读取 authoritative 设置、重建上下文并
 * 逐项比对，任一项对不上都 fail-closed（零写入）。这里**没有**任何绕过字段。
 */
export type AgentSettingsProposalCreateRequest = { sessionId: string, requestId: string, contextId: string, contextHash: string, baseRevision: string | null, patch: PreferenceReadingPatchDto, };
