// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilitySetDto } from "./AgentCapabilitySetDto";

/**
 * Agent 能力清单投影（与领域清单同形；`capabilities` 缺省即全关）。
 */
export type AgentCapabilityManifestDto = { agentApiVersion: number, capabilities: AgentCapabilitySetDto, };
