// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentMediaCapabilityFlagDto = "open_session" | "extract_text" | "render_pages" | "stream";
