// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceComicPatchDto } from "./PreferenceComicPatchDto";
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";

export type AgentResourcePreferencePatchDto = { reading: PreferenceReadingPatchDto | null, comic: PreferenceComicPatchDto | null, };
