// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Broker 当前生命周期状态。它是运行时状态，不是用户授权开关；授权边界仍由
 * Rust Broker 的闭合请求集合与 Proposal 审批链决定。
 */
export type AgentBrokerStatusDto = "disabled" | "listening" | "busy" | "unavailable";
