// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMediaCapabilityDto } from "./AgentMediaCapabilityDto";

export type AgentMediaCapabilitiesDto = { schemaVersion: 1, items: Array<AgentMediaCapabilityDto>, truncated: boolean, };
