// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 拒绝请求：同样只提交提案 ID 与 UI 显示的那份 canonical digest。
 */
export type AgentSettingsProposalRejectRequest = { proposalId: string, expectedDigest: string, };
