// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingsRedactedFieldDto } from "./AgentSettingsRedactedFieldDto";
import type { PreferenceReadingContentWidthDto } from "./PreferenceReadingContentWidthDto";
import type { PreferenceReadingFontFamilyDto } from "./PreferenceReadingFontFamilyDto";
import type { PreferenceReadingFontSizeDto } from "./PreferenceReadingFontSizeDto";
import type { PreferenceReadingFontWeightDto } from "./PreferenceReadingFontWeightDto";
import type { PreferenceReadingLetterSpacingDto } from "./PreferenceReadingLetterSpacingDto";
import type { PreferenceReadingLineHeightDto } from "./PreferenceReadingLineHeightDto";
import type { PreferenceReadingPaginationDto } from "./PreferenceReadingPaginationDto";
import type { PreferenceReadingThemeDto } from "./PreferenceReadingThemeDto";

/**
 * 脱敏后的全局阅读设置快照。
 *
 * 字段名与 `PreferenceReadingSettingsDto` 一致，便于页面直接渲染当前档位；
 * `redactedFields` 里的字段在服务端已被清空（null），页面必须显示为「已脱敏」，
 * 不得当作「未设置」。
 */
export type AgentSettingsReadingSnapshotDto = { section: "reading", fontFamily: PreferenceReadingFontFamilyDto, customFontFamily: string | null, fontSize: PreferenceReadingFontSizeDto, lineHeight: PreferenceReadingLineHeightDto, contentWidth: PreferenceReadingContentWidthDto, theme: PreferenceReadingThemeDto, customBackground: string | null, customText: string | null, fontWeight: PreferenceReadingFontWeightDto, letterSpacing: PreferenceReadingLetterSpacingDto, systemAuto: boolean, pagination: PreferenceReadingPaginationDto, 
/**
 * 服务端脱敏过的字段名（空数组表示没有被裁剪）。
 */
redactedFields: Array<AgentSettingsRedactedFieldDto>, };
