// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent 轨迹事件类型（闭合集合）。事件只描述步骤，不携带模型原文、路径、SQL 或 secret。
 */
export type AgentTraceEventKindDto = "request_started" | "context_loaded" | "provider_request" | "provider_response" | "structured_output_validated" | "proposal_created" | "waiting_for_approval" | "approval_rejected" | "cas_started" | "applied" | "receipt_created" | "cancelled" | "retrying" | "failed";
