// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 按提案 ID 回读资源级 Agent 提案；供未来 UI 从外部 Agent 返回的 proposalId 打开 Diff。
 */
export type AgentResourcePreferenceProposalGetRequest = { proposalId: string, };
