// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentOnboardingStateDto = { schemaVersion: 1, completedSteps: Array<string>, nextStep: string | null, hasStorageLocation: boolean, hasLibraryContent: boolean, hasAiProvider: boolean, };
