// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 能力开关集合。这里是**服务端固定清单**的投影，不是调用方可配置的授权开关。
 */
export type AgentCapabilitySetDto = { settingsRead: boolean, settingsProposal: boolean, librarySummaryRead: boolean, metadataProposal: boolean, renameProposal: boolean, secretRead: boolean, filesystemWrite: boolean, };
