// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMediaAvailabilityDto } from "./AgentMediaAvailabilityDto";
import type { AgentMediaCapabilityFlagDto } from "./AgentMediaCapabilityFlagDto";
import type { MediaTypeDto } from "./MediaTypeDto";

export type AgentMediaCapabilityDto = { mediaItemId: string, mediaType: MediaTypeDto, availability: AgentMediaAvailabilityDto, canOpenSession: boolean, canExtractText: boolean, canRenderPages: boolean, declaredCapabilities: Array<AgentMediaCapabilityFlagDto>, };
