// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingsSectionDto } from "./AgentSettingsSectionDto";

/**
 * 全局设置范围（不含任何作品身份，也不含伪造的 Work ID）。
 */
export type AgentSettingsSubjectDto = { section: AgentSettingsSectionDto, };
