// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResourcePreferenceScopeDto } from "./AgentResourcePreferenceScopeDto";
import type { AgentSettingChangeDto } from "./AgentSettingChangeDto";
import type { AgentSettingsProposalStatusDto } from "./AgentSettingsProposalStatusDto";

export type AgentResourcePreferenceProposalDto = { schemaVersion: 1, proposalId: string, status: AgentSettingsProposalStatusDto, targetScope: AgentResourcePreferenceScopeDto, targetLabel: string, editionId: string, mediaItemId: string | null, baseRevision: string | null, digest: string, createdAt: string, expiresAt: string, changes: Array<AgentSettingChangeDto>, };
