// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingSourceDto } from "./AgentSettingSourceDto";
import type { AgentSettingsSectionDto } from "./AgentSettingsSectionDto";

export type AgentSettingSourcesDto = { schemaVersion: 1, section: AgentSettingsSectionDto, revision: string | null, layers: Array<AgentSettingSourceDto>, };
