// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingSourceLayerDto } from "./AgentSettingSourceLayerDto";

export type AgentSettingSourceDto = { layer: AgentSettingSourceLayerDto, present: boolean, revision: string | null, };
