// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 被服务端脱敏（清空）的字段名。
 */
export type AgentSettingsRedactedFieldDto = "custom_font_family" | "custom_background" | "custom_text";
