// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资源偏好 Agent 作用域。
 */
export type AgentResourcePreferenceScopeDto = "edition" | "media_item";
