// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentCategory } from "./ContentCategory";

export type AgentLibraryRecentItemDto = { workId: string, title: string, category: ContentCategory | null, progressRatio: number | null, };
