// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 用户批准资源级 Agent 提案；目标作用域从持久化 Proposal 重建，不由调用方自带。
 */
export type AgentResourcePreferenceProposalApproveRequest = { proposalId: string, expectedDigest: string, };
