// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingChangeReceiptDto } from "./AgentSettingChangeReceiptDto";
import type { AgentSettingsProposalDto } from "./AgentSettingsProposalDto";

/**
 * 批准结果：应用后的提案状态 + 回执。
 */
export type AgentSettingsProposalApproveResultDto = { proposal: AgentSettingsProposalDto, receipt: AgentSettingChangeReceiptDto, };
