// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 提案读取请求（UI 刷新/重开后回读）。
 */
export type AgentSettingsProposalGetRequest = { proposalId: string, };
