// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentCategory } from "./ContentCategory";

export type AgentLibraryCategoryCountDto = { category: ContentCategory, workCount: bigint, };
