// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 回执读取请求。
 */
export type AgentSettingChangeReceiptGetRequest = { proposalId: string, };
