// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型能力三态。`unknown` 表示 Provider 没有声明该能力，
 * **不**等价于「不支持」，也**不**从模型名推断。
 */
export type AiModelCapabilityDto = "supported" | "unsupported" | "unknown";
