// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiModelCapabilityDto } from "./AiModelCapabilityDto";

/**
 * 一条模型目录记录。能力字段缺失一律 `unknown`。
 */
export type AiProviderModelDto = { modelId: string, displayName: string | null, 
/**
 * Provider 自报的创建时间（Unix 秒）；语义由 Provider 定义。
 */
created: number | null, ownedBy: string | null, chat: AiModelCapabilityDto, vision: AiModelCapabilityDto, embedding: AiModelCapabilityDto, };
