// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderKindDto } from "./AiProviderKindDto";

/**
 * `ai_provider_profile_upsert` 请求。
 *
 * `expectedRevision` 为 null 表示「期望该 profile 尚不存在」；
 * 与当前行不一致时返回冲突且零写入。
 */
export type AiProviderProfileUpsertRequest = { profileId: string, displayName: string, kind: AiProviderKindDto, endpoint: string, enabled: boolean, selectedModelId: string | null, expectedRevision: string | null, };
