// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI Provider 种类（闭合枚举；第一版只有 OpenAI 兼容协议）。
 */
export type AiProviderKindDto = "openai_compatible";
