// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 模型目录状态。`no_credential` / `disabled` / `empty` 都是**诚实空态**而不是错误。
 */
export type AiProviderModelsCatalogStateDto = "ready" | "disabled" | "no_credential" | "empty";
