// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderProfileDto } from "./AiProviderProfileDto";

/**
 * `ai_provider_profile_list` 响应。
 */
export type AiProviderProfileListResultDto = { schemaVersion: 1, profiles: Array<AiProviderProfileDto>, };
