// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 删除结果。凭据清理先于行删除；`credentialDeleted` 只报告事实，不含任何凭据材料。
 */
export type AiProviderProfileDeleteResultDto = { profileId: string, credentialDeleted: boolean, };
