// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderKindDto } from "./AiProviderKindDto";

/**
 * AI Provider Profile 投影。**不含** API key、credentialRef 或凭据 target 名。
 */
export type AiProviderProfileDto = { schemaVersion: 1, profileId: string, displayName: string, kind: AiProviderKindDto, 
/**
 * 用户显式配置的 API 根地址（已通过共享 HTTP URL 策略）。
 */
endpoint: string, enabled: boolean, 
/**
 * 用户选择的模型 id；从未选择时为 null。
 */
selectedModelId: string | null, 
/**
 * 该 profile 的凭据是否已配置（凭据存储只提供存在性，不提供写入时间）。
 */
credentialConfigured: boolean, 
/**
 * CAS 版本号；更新/删除必须原样回传。
 */
revision: string, createdAt: string, updatedAt: string, };
