// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProviderModelDto } from "./AiProviderModelDto";
import type { AiProviderModelsCatalogStateDto } from "./AiProviderModelsCatalogStateDto";

/**
 * `ai_provider_models_list` 响应。
 */
export type AiProviderModelsCatalogDto = { schemaVersion: 1, profileId: string, state: AiProviderModelsCatalogStateDto, models: Array<AiProviderModelDto>, };
