// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `ai_provider_profile_get` 请求。
 */
export type AiProviderProfileGetRequest = { profileId: string, };
