// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 生成智能阅读设置推荐的请求。
 *
 * Provider 只负责返回结构化建议；`contextId`、`contextHash` 与
 * `baseRevision` 必须来自最近一次 authoritative 上下文读取，最终仍停在
 * `pending` Proposal，不包含任何 Apply / Approval / Token 字段。
 */
export type AiSettingsRecommendationGenerateRequest = { profileId: string, sessionId: string, requestId: string, contextId: string, contextHash: string, baseRevision: string | null, };
