// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettingsProposalDto } from "./AgentSettingsProposalDto";
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";

/**
 * Provider 生成的结构化推荐及其待批准 Proposal。
 */
export type AiSettingsRecommendationDto = { schemaVersion: 1, profileId: string, modelId: string, explanation: string | null, recommendedPatch: PreferenceReadingPatchDto, proposal: AgentSettingsProposalDto, };
