// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 受控应用目录。前端只能选择这三个固定范围，不能提交任意路径。
 */
export type AppDirectoryKindDto = "data" | "logs" | "cache";
