// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDirectoryKindDto } from "./AppDirectoryKindDto";

/**
 * About 页面显示的目录投影。`displayPath` 只允许脱敏的逻辑路径，不能包含用户目录名。
 */
export type AppDirectoryDto = { kind: AppDirectoryKindDto, displayName: string, displayPath: string, exists: boolean, canOpen: boolean, };
