// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceAssetKindDto } from "./AppearanceAssetKindDto";

/**
 * 资产导入请求。
 *
 * 这里**没有路径字段**，而且未知字段会被拒绝：WebView 既无法提交裸路径，也无法借
 * 多写一个 `path`/`url` 字段把文件来源换成任意位置——文件只能由后端 Native 文件
 * 选择器选定，伪造的字段会在反序列化边界直接失败。
 */
export type AppearanceAssetImportRequest = { kind: AppearanceAssetKindDto, 
/**
 * 可选展示名；`null` 表示不设置展示名（空字符串会被后端归一化为 `null`）。
 */
displayName: string | null, };
