// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceAssetKindDto } from "./AppearanceAssetKindDto";
import type { AppearanceAssetValidationStateDto } from "./AppearanceAssetValidationStateDto";

/**
 * 外观资产投影。
 *
 * 这里**没有**路径、URL 或原始文件名：资产身份是不透明 `assetId`，字节由后端受控
 * 存储按 ID 解析。`displayName` 是用户可读的展示名（后端已修剪并校验），不是文件
 * 系统上的名字，也不能反向推导出文件位置。
 */
export type AppearanceAssetDto = { assetId: string, kind: AppearanceAssetKindDto, state: AppearanceAssetValidationStateDto, byteSize: number, displayName: string | null, };
