// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资产校验状态（闭合集合）。只有 `validated` 代表字节真的通过了后端校验，
 * 未校验的资产不得被渲染。
 */
export type AppearanceAssetValidationStateDto = "pending" | "validated" | "rejected";
