// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 外观资产种类（闭合集合；与 045 的 `appearance_assets.kind` 同集合）。
 */
export type AppearanceAssetKindDto = "font" | "static_wallpaper" | "dynamic_wallpaper";
