// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceAssetKindDto } from "./AppearanceAssetKindDto";

/**
 * 资产列表请求；`kind` 为 `null` 表示不按种类过滤。
 */
export type AppearanceAssetsListRequest = { kind: AppearanceAssetKindDto | null, };
