// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceAssetDto } from "./AppearanceAssetDto";

/**
 * 资产列表投影（页面 Read Model）。
 */
export type AppearanceAssetsDto = { schemaVersion: 1, assets: Array<AppearanceAssetDto>, };
