// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资产删除结果。
 *
 * 两部分事实分开报告：`deleted` 是「登记行是否被删除」（资产是否存在、也是读路径的
 * 唯一依据）；`fileRemoved` 是「字节是否同时清理成功」。登记行先删，所以
 * `deleted && !fileRemoved` 只意味着留下一个没有任何登记引用的垃圾文件，
 * 不会是「列表里有、字节没有」的不可用资产。
 */
export type AppearanceAssetDeleteResultDto = { deleted: boolean, fileRemoved: boolean, };
