// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资产删除请求（只有不透明资产 ID）。
 */
export type AppearanceAssetDeleteRequest = { assetId: string, };
