// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppDirectoryDto } from "./AppDirectoryDto";
import type { ThirdPartyNoticeDto } from "./ThirdPartyNoticeDto";

/**
 * About/Diagnostics 查询。只返回构建和脱敏运行时信息，不返回 Secret、完整路径或用户内容。
 */
export type AppInfoDto = { schemaVersion: 1, appVersion: string, buildChannel: string, sourcePackVersion: string | null, protocolVersion: string, databaseVersion: string, appLicense: string | null, thirdPartyNotices: Array<ThirdPartyNoticeDto>, directories: Array<AppDirectoryDto>, };
