// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAnchorDto } from "./TextAnchorDto";

export type ArticleLocatorDto = { blockId: string | null, progression: number | null, textAnchor: TextAnchorDto | null, };
