// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource 可用性摘要；后端是唯一事实来源，前端不得自行推断。
 */
export type AvailabilityDto = "available" | "offline_available" | "temporarily_unavailable" | "source_unavailable" | "storage_unavailable" | "missing" | "unknown";
