// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheScopeDto } from "./CacheScopeDto";

/**
 * `cache_clear` 结果；仅返回清理范围和条目数量，不返回路径。
 */
export type CacheClearResultDto = { scope: CacheScopeDto, removedEntries: bigint, };
