// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可清理的技术缓存范围；业务事实、离线资源和原始媒体不在此枚举内。
 */
export type CacheScopeDto = "artwork" | "thumbnails" | "provider-response-cache";
