// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEngineDto } from "./SessionEngineDto";

/**
 * `cast_play` 请求。
 */
export type CastPlayRequest = { mediaItemId: string, deviceId: string, engine: SessionEngineDto, };
