// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastProtocolDto } from "./CastProtocolDto";

/**
 * 投屏设备投影（仅含发现与控制所需最小信息；控制 URL 不出 IPC）。
 */
export type CastDeviceDto = { deviceId: string, friendlyName: string, ip: string, protocol: CastProtocolDto, modelName: string | null, };
