// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 投屏传输状态（与 AVTransport / CastV2 映射）。
 */
export type CastTransportStateDto = "playing" | "paused" | "stopped" | "no_media" | "transitioning" | "unknown";
