// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastTransportStateDto } from "./CastTransportStateDto";

/**
 * `cast_status` 结果。
 */
export type CastStatusDto = { schemaVersion: 1, transportState: CastTransportStateDto, positionMs: number | null, durationMs: number | null, };
