// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cast_discover` 请求。
 */
export type CastDiscoverRequest = { 
/**
 * 超时毫秒（null → 默认 5000；>10000 → INVALID_ARGUMENT）。
 */
timeoutMs: number | null, };
