// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cast_stop` 结果。
 */
export type CastStopResult = { schemaVersion: 1, stopped: boolean, };
