// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cast_play` 结果。
 */
export type CastPlayResult = { schemaVersion: 1, castSessionId: string, lanUrl: string, deviceName: string, };
