// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastDeviceDto } from "./CastDeviceDto";

/**
 * `cast_discover` 结果。
 */
export type CastDiscoverResult = { schemaVersion: 1, devices: Array<CastDeviceDto>, };
