// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 授权尝试状态（闭合集合，与 Application `CloudConnectStatus` 逐项对应）。
 */
export type CloudConnectStatusDto = "pending" | "completing" | "authorized" | "cancelled" | "expired" | "failed" | "completed";
