// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 浏览条目：只有不透明句柄与展示事实；`handle = null` 表示当前不可选。
 */
export type CloudBrowseEntryDto = { handle: string | null, displayName: string, isFolder: boolean, pdfSupported: boolean, sizeBytes: number | null, };
