// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudAccountDto } from "./CloudAccountDto";

/**
 * `cloud_storage_list` 响应：本机是否已配置授权 + 全部账户（含断开墓碑）。
 */
export type CloudStorageListDto = { oauthAvailable: boolean, accounts: Array<CloudAccountDto>, };
