// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 账户投影：内部 UUID 与非敏感事实（无 Provider 身份、无凭据引用、无邮箱）。
 */
export type CloudAccountDto = { id: string, displayName: string, connected: boolean, 
/**
 * 账户代际：断开与重新授权都会前进；写操作必须带着它做 CAS。
 */
generation: number, };
