// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudBrowseEntryDto } from "./CloudBrowseEntryDto";

/**
 * 一页浏览结果：条目 + 一次性光标 + 本页所属目录句柄（三者都只是句柄）。
 */
export type CloudBrowsePageDto = { folderHandle: string | null, entries: Array<CloudBrowseEntryDto>, nextCursor: string | null, };
