// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cloud_account_connect_begin` 请求：`accountId` 省略或 `null` 即新连接。
 */
export type CloudConnectBeginRequest = { accountId?: string, };
