// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cloud_register_folder` 请求：不透明目录句柄 + 用户起的显示名。
 */
export type CloudRegisterFolderRequest = { folderHandle: string, displayName: string, };
