// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudConnectStatusDto } from "./CloudConnectStatusDto";

/**
 * `cloud_account_connect_poll` 响应：轮询到的状态与到期时刻。
 */
export type CloudConnectPollDto = { status: CloudConnectStatusDto, expiresAtMs: number, };
