// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入对象投影：全部是内部 UUID（对象 / 媒体条目 / 资源）与展示事实。
 */
export type CloudObjectDto = { objectId: string, mediaItemId: string, resourceId: string, displayName: string, sizeBytes: number, };
