// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cloud_account_connect_begin` 响应：本地授权尝试句柄与到期时刻。
 */
export type CloudConnectAttemptDto = { attemptId: string, expiresAtMs: number, };
