// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cloud_import_pdf` 请求：内部位置 UUID + 该目录下浏览得到的文件句柄。
 */
export type CloudImportPdfRequest = { locationId: string, fileHandle: string, };
