// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cloud_account_disconnect` 请求：内部账户 UUID + 调用方读到的代际（CAS）。
 */
export type CloudAccountDisconnectRequest = { accountId: string, expectedGeneration: number, };
