// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicScanGroupKindDto = "unknown" | "content_line" | "mirror_label" | "not_applicable";
