// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicChapterMatchKindDto = "same_remote_chapter" | "same_content" | "same_logical_chapter_variant" | "candidate" | "unrelated";
