// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicEditionProfileDto } from "./ComicEditionProfileDto";

export type ComicWorkEditionDto = { editionId: string, profile: ComicEditionProfileDto, displayLabel: string, chapterCount: number, };
