// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceCandidateDto } from "./ComicChapterSourceCandidateDto";
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";

/**
 * 当前来源章节的候选集合。候选按后端证据排序，`truncated=true` 表示
 * Work 下的来源引用超过本次安全返回上限；它不是“没有更多章节”的判断。
 */
export type ComicChapterSourceCandidatesDto = { schemaVersion: 1, source: ComicChapterSourceIdentityDto, currentMediaItemId: string, candidates: Array<ComicChapterSourceCandidateDto>, truncated: boolean, };
