// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";

/**
 * 跨来源章节迁移请求。低置信度 `Suggested` 匹配只有在用户或应用策略明确
 * 允许最佳努力迁移时才会写入；目标已有进度默认保留，只有用户明确选择覆盖
 * 时才允许 `allowTargetOverwrite=true`；源/目标 revision 仍由后端在原子事务中校验。
 */
export type ComicProgressMigrationRequestDto = { source: ComicChapterSourceIdentityDto, target: ComicChapterSourceIdentityDto, 
/**
 * 允许低置信度元数据匹配执行可撤销的最佳努力迁移。
 */
allowBestEffort: boolean, 
/**
 * 只有用户明确选择覆盖目标现有进度时才设为 true。
 */
allowTargetOverwrite: boolean, };
