// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterEvidenceDto } from "./ComicChapterEvidenceDto";
import type { ComicChapterMatchKindDto } from "./ComicChapterMatchKindDto";
import type { ComicMatchConfidenceDto } from "./ComicMatchConfidenceDto";
import type { ComicProgressMigrationModeDto } from "./ComicProgressMigrationModeDto";

export type ComicChapterMatchDto = { kind: ComicChapterMatchKindDto, confidence: ComicMatchConfidenceDto, progressMigration: ComicProgressMigrationModeDto, evidence: Array<ComicChapterEvidenceDto>, };
