// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicPageMappingConfidenceDto } from "./ComicPageMappingConfidenceDto";
import type { ComicPageMappingStrategyDto } from "./ComicPageMappingStrategyDto";

export type ComicPageMigrationDto = { targetPageIndex: number | null, confidence: ComicPageMappingConfidenceDto, strategy: ComicPageMappingStrategyDto, reversible: boolean, };
