// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicCatalogRefreshOutcomeStatusDto = "never_synced" | "succeeded" | "temporarily_unavailable" | "external_only" | "unknown" | "refresh_failed" | "truncated";
