// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicPageAvailabilityDto } from "./ComicPageAvailabilityDto";

/**
 * 漫画页公开投影。pageId 是逻辑身份，contentUri 是独立的读取 capability。
 */
export type ComicPageDto = { pageId: string, pageIndex: number, availability: ComicPageAvailabilityDto, contentUri: string | null, };
