// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicChapterEvidenceKindDto = "same_remote_identity" | "authoritative_content_key" | "conflicting_authoritative_content_key" | "edition_compatible" | "edition_conflict" | "exact_page_identity" | "partial_page_identity" | "matching_chapter_metadata" | "weak_chapter_metadata";
