// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work 级漫画目录请求。这里只携带本地 Work/MediaItem 身份；二选一的业务
 * 约束由命令/Application 核心校验，serde 层只负责字段闭合和兼容反序列化。
 */
export type ComicWorkChapterCatalogRequestDto = { workId: string | null, mediaItemId: string | null, };
