// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";

/**
 * 获取当前章节已经登记的其他来源候选。请求中的来源身份必须先在
 * SQLite 中解析，前端不能用它直接构造 Provider URL 或资源定位器。
 */
export type ComicChapterSourceCandidatesGetRequestDto = { source: ComicChapterSourceIdentityDto, };
