// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";
import type { ComicChapterSourceStatusDto } from "./ComicChapterSourceStatusDto";

export type ComicChapterSourceSummaryDto = { source: ComicChapterSourceIdentityDto, status: ComicChapterSourceStatusDto, mirrorLabel: string | null, observedAt: string | null, sourceOrder: number, };
