// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicCatalogRefreshReceiptDto } from "./ComicCatalogRefreshReceiptDto";
import type { ComicWorkCatalogStatusDto } from "./ComicWorkCatalogStatusDto";
import type { ComicWorkChapterDto } from "./ComicWorkChapterDto";
import type { ComicWorkEditionDto } from "./ComicWorkEditionDto";

export type ComicWorkChapterCatalogDto = { schemaVersion: 1, workId: string, currentMediaItemId: string | null, editions: Array<ComicWorkEditionDto>, chapters: Array<ComicWorkChapterDto>, refreshStatus: ComicWorkCatalogStatusDto, lastObservedAt: string | null, truncated: boolean, refreshReceipts: Array<ComicCatalogRefreshReceiptDto>, };
