// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 获取一个来源作品当前章节目录的只读请求。
 */
export type ComicChapterCatalogGetRequest = { sourceId: string, remoteWorkId: string, };
