// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterCatalogRefreshStateDto } from "./ComicChapterCatalogRefreshStateDto";
import type { ComicRegisteredChapterCatalogItemDto } from "./ComicRegisteredChapterCatalogItemDto";

export type ComicRegisteredChapterCatalogDto = { schemaVersion: 1, sourceId: string, remoteWorkId: string, refreshState: ComicChapterCatalogRefreshStateDto | null, chapters: Array<ComicRegisteredChapterCatalogItemDto>, };
