// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterAvailabilityDto } from "./ComicChapterAvailabilityDto";
import type { ComicEditionProfileDto } from "./ComicEditionProfileDto";

export type ComicChapterCatalogItemDto = { 
/**
 * Provider 章节 ID 作为 opaque identity 返回；所有消费命令仍由后端复核。
 */
remoteChapterId: string, chapterNumber: number | null, volumeNumber: number | null, title: string | null, pageCount: number | null, publishedAt: string | null, updatedAt: string | null, availability: ComicChapterAvailabilityDto, editionProfile: ComicEditionProfileDto, };
