// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterAggregateStatusDto } from "./ComicChapterAggregateStatusDto";
import type { ComicChapterMatchDto } from "./ComicChapterMatchDto";
import type { ComicChapterSourceSummaryDto } from "./ComicChapterSourceSummaryDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

export type ComicWorkChapterDto = { mediaItemId: string, editionId: string, subjectId: string | null, chapterNumber: number | null, volumeNumber: number | null, title: string | null, publishedAt: string | null, pageCount: number | null, status: ComicChapterAggregateStatusDto, canOpen: boolean, sources: Array<ComicChapterSourceSummaryDto>, matchResult: ComicChapterMatchDto | null, progress: ProgressSummaryDto | null, previousMediaItemId: string | null, nextMediaItemId: string | null, backendOrder: number, };
