// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterMatchDto } from "./ComicChapterMatchDto";
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";
import type { ComicChapterSourceStatusDto } from "./ComicChapterSourceStatusDto";
import type { ComicEditionProfileDto } from "./ComicEditionProfileDto";

/**
 * 一个来源章节候选的安全展示投影。`matchResult` 是后端比较出的证据，
 * 不允许前端自行以标题、章节号或页数写回数据库。
 */
export type ComicChapterSourceCandidateDto = { source: ComicChapterSourceIdentityDto, mediaItemId: string, chapterNumber: number | null, volumeNumber: number | null, title: string | null, pageCount: number | null, sourceOrder: number, availability: ComicChapterSourceStatusDto, publishedAt: string | null, sourceUpdatedAt: string | null, lastSeenGeneration: number | null, editionProfile: ComicEditionProfileDto, matchResult: ComicChapterMatchDto, };
