// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceIdentityDto } from "./ComicChapterSourceIdentityDto";

/**
 * 跨来源章节迁移请求。目标已有进度默认保留，只有用户明确选择覆盖时才允许
 * `allowTargetOverwrite=true`；源/目标 revision 仍由后端在原子事务中校验。
 */
export type ComicProgressMigrationRequestDto = { source: ComicChapterSourceIdentityDto, target: ComicChapterSourceIdentityDto, allowTargetOverwrite: boolean, };
