// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicCatalogRefreshOutcomeStatusDto } from "./ComicCatalogRefreshOutcomeStatusDto";

export type ComicCatalogRefreshReceiptDto = { refreshId: string, workId: string, sourceId: string, remoteWorkId: string, status: ComicCatalogRefreshOutcomeStatusDto, generationBefore: number, generationAfter: number | null, observedFrom: string | null, observedTo: string | null, truncated: boolean, retainedPreviousCatalog: boolean, errorCode: string | null, observedAt: string, };
