// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicColorModeDto } from "./ComicColorModeDto";
import type { ComicEditionFacetKindDto } from "./ComicEditionFacetKindDto";
import type { ComicScanGroupKindDto } from "./ComicScanGroupKindDto";

/**
 * 章节目录中用于展示 Edition 区分依据的安全画像。
 *
 * 只投影已清洗的标签和语义 kind；不投影 URL、pageId、grant、请求头或
 * provider 内部页面定位。
 */
export type ComicEditionProfileDto = { language: string | null, languageKind: ComicEditionFacetKindDto, translationLine: string | null, translationLineKind: ComicEditionFacetKindDto, scanGroup: string | null, scanGroupKind: ComicScanGroupKindDto, colorMode: ComicColorModeDto, };
