// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicPageMappingStrategyDto = "stable_key" | "content_fingerprint" | "reordered_anchor" | "nearest_surviving_page" | "proportional_fallback" | "no_target";
