// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicProgressMigrationStatusDto = "unchanged" | "not_applicable" | "applied" | "shared_content" | "suggested" | "no_source_progress" | "target_progress_preserved" | "no_target_page";
