// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 漫画章节目录的来源可用性。不可用章节也会进入只读目录投影，供刷新层
 * 区分暂时不可用、外部跳转和字段不完整，而不是被前端误认为已删除。
 */
export type ComicChapterAvailabilityDto = "available" | "temporarily_unavailable" | "external_only" | "unknown";
