// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComicProgressMigrationModeDto = "shared" | "one_time" | "suggested" | "none";
