// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterEvidenceDto } from "./ComicChapterEvidenceDto";
import type { ComicPageMappingConfidenceDto } from "./ComicPageMappingConfidenceDto";
import type { ComicPageMappingStrategyDto } from "./ComicPageMappingStrategyDto";
import type { ComicPageMigrationDto } from "./ComicPageMigrationDto";
import type { ComicProgressSnapshotDto } from "./ComicProgressSnapshotDto";

export type ComicProgressMigrationReceiptDto = { migrationId: string, sourceMediaItemId: string, targetMediaItemId: string, strategy: ComicPageMappingStrategyDto, confidence: ComicPageMappingConfidenceDto, evidence: Array<ComicChapterEvidenceDto>, sourceProgressSnapshot: ComicProgressSnapshotDto | null, targetProgressBefore: ComicProgressSnapshotDto | null, targetProgressAfter: ComicProgressSnapshotDto | null, pageMapping: ComicPageMigrationDto, algorithmVersion: string, createdAt: string, undoable: boolean, appliedRevision: string | null, };
