// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterMatchDto } from "./ComicChapterMatchDto";
import type { ComicPageMigrationDto } from "./ComicPageMigrationDto";
import type { ComicProgressMigrationStatusDto } from "./ComicProgressMigrationStatusDto";

/**
 * 章节换源/页面重定位的统一结果。低置信度自动迁移也必须带 snapshotId，
 * 以便用户在目标进度未被后续写入时撤销。
 */
export type ComicProgressMigrationResultDto = { status: ComicProgressMigrationStatusDto, matchResult: ComicChapterMatchDto | null, pageMigration: ComicPageMigrationDto, snapshotId: string | null, appliedRevision: string | null, };
