// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 当前 Session 内某一页的可用性。不可用页保留 pageIndex，不让后续页重排。
 */
export type ComicPageAvailabilityDto = "ready" | "unavailable";
