// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterEvidenceKindDto } from "./ComicChapterEvidenceKindDto";

/**
 * 证据保持为闭合 kind + 可选计数，避免把 Domain enum 的内部表示直接暴露给 IPC。
 */
export type ComicChapterEvidenceDto = { kind: ComicChapterEvidenceKindDto, matched: number | null, };
