// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionWire } from "./CompletionWire";

export type ComicProgressSnapshotDto = { mediaItemId: string, pageIndex: number | null, pageProgression: number | null, completion: CompletionWire, percentage: number | null, revision: string | null, updatedAt: string | null, };
