// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterSourceStatusDto } from "./ComicChapterSourceStatusDto";
import type { ComicEditionProfileDto } from "./ComicEditionProfileDto";

/**
 * SQLite 中已经登记的章节安全投影。
 *
 * 与 Provider 观察目录分开建模：这里返回 Haven `mediaItemId` 和已持久化的
 * 来源状态，供章节列表、换源和进度迁移使用；内部 Resource locator、URL、
 * pageId、grant、请求头和 authoritative content key 永不进入 Wire。
 */
export type ComicRegisteredChapterCatalogItemDto = { mediaItemId: string, sourceId: string, remoteWorkId: string, remoteChapterId: string, chapterNumber: number | null, volumeNumber: number | null, title: string | null, pageCount: number | null, sourceOrder: number, availability: ComicChapterSourceStatusDto, publishedAt: string | null, sourceUpdatedAt: string | null, lastSeenGeneration: number | null, editionProfile: ComicEditionProfileDto, };
