// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 重新检查 owner-bound Comic Session 的页面序列并迁移进度。
 *
 * 页面身份必须由后端重新 inspect 生成；前端不能提交旧/新页面身份，
 * 也不能把运行时 pageId、grant、URL 或路径伪装成迁移证据。
 */
export type ComicPageProgressRemapRequestDto = { sessionId: string, expectedRevision: string | null, };
