// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 页面稳定身份。两个字段都为空时表示调用方没有可用页面证据，
 * 允许应用层选择可撤销的比例兜底。
 */
export type ComicPageIdentityDto = { stableKey: string | null, fingerprint: string | null, };
