// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicPageDto } from "./ComicPageDto";

/**
 * 当前 Comic Session 的稳定页面清单。pageIndex 严格连续且从 0 开始。
 */
export type ComicPageManifestDto = { schemaVersion: 1, sessionId: string, mediaItemId: string, pageCount: number, pages: Array<ComicPageDto>, };
