// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 已登记章节的来源状态。`Missing` 只表示最近一次完整刷新没有再次看到
 * 该章节；MediaItem、Progress、Marker、History 仍然保留。
 */
export type ComicChapterSourceStatusDto = "available" | "temporarily_unavailable" | "external_only" | "unknown" | "missing";
