// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComicChapterCatalogItemDto } from "./ComicChapterCatalogItemDto";

export type ComicChapterCatalogDto = { schemaVersion: 1, sourceId: string, remoteWorkId: string, fetchedAt: string, total: number | null, truncated: boolean, chapters: Array<ComicChapterCatalogItemDto>, };
