// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一个章节在某个来源上的 opaque 身份。来源/作品/章节 ID 由后端重新校验，
 * 不表示 URL、资源路径或运行时 pageId。
 */
export type ComicChapterSourceIdentityDto = { sourceId: string, remoteWorkId: string, remoteChapterId: string, };
