// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 完成状态（闭合集合；NOTE-2：请求与响应共用，禁止裸 String）。
 */
export type CompletionWire = "not_started" | "in_progress" | "completed" | "abandoned";
