// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一级分类（canonical，无 `all`——`all` 只作为查询 sentinel）。
 */
export type ContentCategory = "video" | "book" | "comic" | "periodical";
