// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

/**
 * Continue 条目（首页 `home_get`；NOTE-7 契约定义）。
 */
export type ContinueItemDto = { workId: string, mediaItemId: string, progress: ProgressSummaryDto, primaryAction: PrimaryActionDto, };
