// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 凭据状态投影（契约 §36.5）。secret/credentialRef/target 名禁止出 IPC；
 * 凭据存储不提供写入时间时 updatedAt 为 null。
 */
export type CredentialStatusDto = { configured: boolean, updatedAt: string | null, };
