// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialProviderDto } from "./CredentialProviderDto";

/**
 * `credential_status` 请求；profileId=null 表示默认 profile（"default"）。
 */
export type CredentialStatusRequest = { provider: CredentialProviderDto, profileId: string | null, };
