// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialProviderDto } from "./CredentialProviderDto";

/**
 * `credential_delete` 请求。幂等；不存在视为成功。
 */
export type CredentialDeleteRequest = { provider: CredentialProviderDto, profileId: string | null, };
