// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 凭据 Provider（契约 §36.5 闭合枚举；v0.2 仅 webdav）。
 */
export type CredentialProviderDto = "webdav" | "opds";
