// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialProviderDto } from "./CredentialProviderDto";

/**
 * `credential_set` 请求。Secret 单向写入 Windows Credential Store，
 * 幂等覆盖；任何响应/事件/日志不得回显。
 */
export type CredentialSetRequest = { provider: CredentialProviderDto, profileId: string | null, secret: string, };
