// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadMutationResultDto = { schemaVersion: 1, taskId: string, recordRemoved: boolean, offlineResourceRemoved: boolean, };
