// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下载任务状态（与 Domain DownloadState 一一对应；Finalizing 等未纳入 v0.1）。
 */
export type DownloadStateDto = "queued" | "resolving" | "downloading" | "paused" | "verifying" | "completed" | "failed" | "cancelled" | "interrupted";
