// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStateDto } from "./DownloadStateDto";

export type DownloadEventData = { taskId: string, state: DownloadStateDto, offlineResourceId: string | null, bytesTotal: number | null, bytesDownloaded: number, speedBps: number | null, etaSeconds: number | null, 
/**
 * 终态失败/中断的稳定错误码；普通进度事件为 null。
 */
errorCode: string | null, };
