// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentCategory } from "./ContentCategory";
import type { DownloadStateDto } from "./DownloadStateDto";
import type { MediaTypeDto } from "./MediaTypeDto";

export type DownloadTaskDto = { schemaVersion: 1, taskId: string, workId: string | null, editionId: string | null, mediaItemId: string | null, sourceResourceId: string, targetStorageId: string, offlineResourceId: string | null, title: string, mediaType: MediaTypeDto, category: ContentCategory, posterUri: string | null, state: DownloadStateDto, bytesTotal: number | null, bytesDownloaded: number, speedBps: number | null, etaSeconds: number | null, progressRatio: number | null, batchId?: string | null, createdAt: string, updatedAt: string, };
