// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadEventData } from "./DownloadEventData";
import type { DownloadEventKind } from "./DownloadEventKind";

export type DownloadEvent = { operationId: string, sequence: number, at: string, kind: DownloadEventKind, data: DownloadEventData, };
