// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaItemSummaryDto } from "./MediaItemSummaryDto";
import type { MediaTypeDto } from "./MediaTypeDto";

/**
 * Edition 详情页的真实消费单元投影。内部路径、Resource 和数据库 Row 不进入 Wire。
 */
export type EditionDetailDto = { schemaVersion: 1, editionId: string, workId: string, title: string, subtitle: string | null, mediaType: MediaTypeDto, releaseDate: string | null, language: string | null, region: string | null, publisherOrStudio: string | null, description: string | null, items: Array<MediaItemSummaryDto>, };
