// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditionAvailabilityDto } from "./EditionAvailabilityDto";
import type { MediaTypeDto } from "./MediaTypeDto";
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

export type EditionSummaryDto = { editionId: string, workId: string, title: string, subtitle: string | null, mediaType: MediaTypeDto, releaseDate: string | null, language: string | null, region: string | null, mediaItemCount: number, availability: EditionAvailabilityDto, progress: ProgressSummaryDto | null, primaryAction: PrimaryActionDto | null, download: string | null, };
