// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enrichment 状态（契约 §36.8 闭合枚举）。
 */
export type EnrichmentStatusWire = "pending" | "enriched" | "failed";
