// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnrichmentStatusWire } from "./EnrichmentStatusWire";

/**
 * 单条 enrichment 记录投影。error 为安全文案，不含内部路径/远端响应。
 */
export type EnrichmentStateDto = { workId: string, status: EnrichmentStatusWire, sourceId: string | null, error: string | null, };
