// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorReportDetailsDto } from "./ErrorReportDetailsDto";
import type { ErrorReportLevelDto } from "./ErrorReportLevelDto";
import type { ErrorReportRedactionDto } from "./ErrorReportRedactionDto";

/**
 * 预览与导出共用的脱敏报告投影。该 DTO 可安全展示在设置页，不能反向推导
 * 数据库路径、媒体内容、搜索词、Cookie 或任何 Secret。
 */
export type ErrorReportPreviewDto = { schemaVersion: 1, reportId: string, level: ErrorReportLevelDto, createdAt: string, appVersion: string, operatingSystem: string, runtimeMode: string, stableErrorCodes: Array<string>, errorSummary: string, redaction: ErrorReportRedactionDto, details: ErrorReportDetailsDto | null, requiresConfirmation: boolean, };
