// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorReportRedactionStatusDto } from "./ErrorReportRedactionStatusDto";

export type ErrorReportRedactionDto = { status: ErrorReportRedactionStatusDto, 
/**
 * 只列出被移除的敏感类别，不列出原文或路径。
 */
removedFields: Array<string>, containsSensitiveData: boolean, };
