// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorReportActionStatusDto } from "./ErrorReportActionStatusDto";

export type ErrorReportActionResultDto = { schemaVersion: 1, reportId: string, status: ErrorReportActionStatusDto, };
