// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorReportLevelDto } from "./ErrorReportLevelDto";

/**
 * 预览请求只允许选择等级并带入有限的稳定错误码；错误码由 Application
 * 严格校验为大写标识符，前端不能传递消息正文、URL、路径或 Headers。
 */
export type ErrorReportPreviewRequest = { level: ErrorReportLevelDto, stableErrorCodes: Array<string>, };
