// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 标准/详细等级额外显示的安全运行上下文。diagnosticLines 只允许稳定错误摘要，
 * 不承载日志正文、URL 或本地路径。
 */
export type ErrorReportDetailsDto = { protocolVersion: string | null, databaseVersion: string | null, sourcePackVersion: string | null, diagnosticLines: Array<string>, };
