// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 诊断报告收集等级。等级只扩大脱敏后的运行时摘要，不会包含用户内容、凭据
 * 或完整路径；详细日志必须由后端先经过脱敏检查。
 */
export type ErrorReportLevelDto = "basic" | "standard" | "detailed";
