// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire 错误（C-02 冻结：ErrorDto 进入单一生成源；前端依据 code 决定
 * 回滚/刷新/重试/导航；retryable 由后端错误分类）。
 */
export type ErrorDto = { 
/**
 * 稳定错误码（v1 Error Catalog，见契约 §13）。
 */
code: string, 
/**
 * 可展示给用户的文案（前端不得拼后端内部消息）。
 */
userMessage: string, 
/**
 * true 时允许用户重试（平台暂时性错误），false 时重试无意义。
 */
retryable: boolean, };
