// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 脱敏检查的明确结果。导出和打开 Issue 前必须为 Passed。
 */
export type ErrorReportRedactionStatusDto = "passed" | "failed";
