// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 第三方元数据 Provider（契约 §36.1 闭合枚举；扩展需契约修订）。
 */
export type ExternalIdProviderDto = "tmdb" | "bangumi" | "anilist" | "tvmaze" | "gutenberg" | "openlibrary";
