// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalIdProviderDto } from "./ExternalIdProviderDto";

/**
 * 元数据去重键投影（契约 §36.1）。`(provider, externalId)` 在同一 Work 内唯一；
 * Enrichment 匹配成功才写入，失败不产生占位条目。
 */
export type ExternalIdDto = { provider: ExternalIdProviderDto, externalId: string, };
