// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `favorite_set` 请求（Work 收藏目标；幂等）。
 */
export type FavoriteSetRequest = { workId: string, favorite: boolean, };
