// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `favorite_set` 成功响应（R-C01 冻结；名称与形状固定）。
 * revision 语义（R-FAV-001，状态版本）：
 * - 状态变化（未收藏↔收藏）→ 生成新 revision 并持久化（work_favorite_versions）。
 * - 重复设置相同状态 → 返回当前 revision，**不制造新 token**（幂等收敛）。
 * - 从未变更过状态（无版本历史）→ `revision: null`（favorite 字段为权威状态；
 *   幂等路径不发 Event，因此 Event 的 revision 恒非空 string）。
 */
export type FavoriteSetResult = { workId: string, favorite: boolean, revision: string | null, };
