// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `favorite.changed` 事件负载（C-03 / R-FAV-001 冻结）。
 * revision 与 `FavoriteSetResult.revision` 同源（状态版本）；重复设置相同状态
 * 不发布本事件，因此事件携带的 revision 恒非空。
 */
export type FavoriteChangedDto = { schemaVersion: 1, at: string, operationId: string, sequence: number, workId: string, favorite: boolean, revision: string, };
