// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

/**
 * 历史条目投影（契约 §23：列表 Item 带目标类型与明确 ID）。
 */
export type HistoryEntryDto = { historyEntryId: string, mediaItemId: string, workId: string, editionId: string, startedAt: string, lastActiveAt: string, completedAt: string | null, 
/**
 * 精确指向此历史条目的消费目标；绝不能从同一 Work 的首集或当前卡片投影推断。
 */
primaryAction: PrimaryActionDto | null, 
/**
 * 此历史条目 MediaItem 的当前进度（如有）；展示时不得以另一集的进度替代。
 */
progress: ProgressSummaryDto | null, };
