// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `history_list` 请求（契约 §23.1）：最近活跃历史。
 * `limit` 为 None 时由后端取默认上限（MAX_LIMIT）。
 */
export type HistoryListRequest = { limit: number | null, };
