// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 历史条目投影（契约 §23：列表 Item 带目标类型与明确 ID）。
 */
export type HistoryEntryDto = { historyEntryId: string, mediaItemId: string, workId: string, editionId: string, startedAt: string, lastActiveAt: string, completedAt: string | null, };
