// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 历史聚合摘要（契约 §36.7）。
 */
export type HistorySummaryDto = { lastOpenedAt: string, openCount: number, };
