// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeLayoutDto } from "./HomeLayoutDto";

/**
 * 首页布局写入请求。`expectedRevision` 是上一次读取到的 revision；从未保存过时必须
 * 回传 `null`。对不上 → `REVISION_CONFLICT`（零写入）。
 */
export type HomeLayoutSaveRequest = { expectedRevision: string | null, layout: HomeLayoutDto, };
