// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 首页模块档位（闭合集合）。档位决定模块在网格里占几列。
 */
export type HomeModuleSizeDto = "small" | "medium" | "large";
