// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeModuleIdDto } from "./HomeModuleIdDto";
import type { HomeModuleSizeDto } from "./HomeModuleSizeDto";

/**
 * 首页模块放置：模块、档位与网格**起始格**坐标。
 */
export type HomeModulePlacementDto = { module: HomeModuleIdDto, size: HomeModuleSizeDto, row: number, column: number, order: number, };
