// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeLayoutDto } from "./HomeLayoutDto";

/**
 * 首页布局写入结果。`changed` 为 `false` 表示请求的布局与已保存的规范形态一致
 * （幂等重放），此时 `revision` 不变。
 */
export type HomeLayoutMutationResultDto = { layout: HomeLayoutDto, revision: string | null, changed: boolean, };
