// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeLayoutDto } from "./HomeLayoutDto";

/**
 * 首页布局读取结果。`revision` 为 `null` 表示**从未保存过**自定义布局，此时
 * `layout` 是领域默认布局；它与「保存了空布局」（`revision` 非 null 且 `modules` 为空）
 * 是两种不同事实。
 */
export type HomeLayoutSnapshotDto = { layout: HomeLayoutDto, revision: string | null, };
