// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeModulePlacementDto } from "./HomeModulePlacementDto";

/**
 * 首页布局。空 `modules` 是合法的显式自定义（用户隐藏了全部模块），
 * 与「从未保存过」是两种不同事实（后者由 `revision` 为 `null` 表达）。
 */
export type HomeLayoutDto = { schemaVersion: 1, modules: Array<HomeModulePlacementDto>, };
