// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 首页模块 ID（闭合集合）。
 *
 * 逐项写出 wire 值而不是用 `rename_all`：`shelf-favorites` 是**连字符**，会被
 * `snake_case` 悄悄改成下划线（那会变成另一个模块 ID，与 HomeService 的 `shelf_id` 不一致）。
 */
export type HomeModuleIdDto = "continue" | "recently_added" | "shelf-favorites";
