// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContinueItemDto } from "./ContinueItemDto";
import type { ShelfDto } from "./ShelfDto";
import type { WorkCardDto } from "./WorkCardDto";

/**
 * 首页投影（`home_get`；NOTE-7 契约定义）。
 */
export type HomeDto = { schemaVersion: 1, continueItems: Array<ContinueItemDto>, recentlyAdded: Array<WorkCardDto>, shelves: Array<ShelfDto>, };
