// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 按钮文案提示（闭合联合，C-04 修复：前端可 exhaustive render，
 * 未知值不得静默落入默认分支）。
 */
export type LabelHint = "start" | "continue" | "open";
