// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Library 列表排序。
 */
export type LibraryListSort = "recently_added" | "title" | "last_active" | "release_date" | "rating";
