// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `library.changed` 事件负载（C-03 冻结）。
 * 语义：只携带失效信号，不复制页面状态；完整数据由 Query 拉取。
 * 乱序/重复：sequence 单调递增（同一 operation 内），消费者按 sequence
 * 丢弃旧事件；重复投递幂等（revision 与本地比对，旧则忽略）。
 */
export type LibraryChangedDto = { schemaVersion: 1, 
/**
 * RFC3339 投递时间。
 */
at: string, operationId: string, 
/**
 * 事件源内递增序号（乱序检测）。
 */
sequence: number, 
/**
 * 列表缓存失效用 revision（与 PageDto.revision 同源；`null` 表示全量刷新）。
 */
revision: string | null, };
