// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryListSort } from "./LibraryListSort";
import type { MediaTypeDto } from "./MediaTypeDto";
import type { QueryCategory } from "./QueryCategory";

/**
 * `library_list` 请求（契约 §14.3）。
 */
export type LibraryListRequest = { category: QueryCategory, mediaTypes: Array<MediaTypeDto> | null, query: string | null, sort: LibraryListSort, cursor: string | null, limit: number, };
