// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录选择若在后续版本需要，必须走受控注册流程签发的 opaque scope token。
 */
export type LibraryScanStartRequest = { storageLocationId: string, };
