// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShelfDto } from "./ShelfDto";

/**
 * `library_shelves` 顶层响应（C-05 冻结裁决：版本在顶层，不散落到每个 Shelf）。
 */
export type LibraryShelvesDto = { schemaVersion: 1, 
/**
 * 空列表固定返回 `[]`，不返回 `null`。
 */
shelves: Array<ShelfDto>, };
