// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanEventData } from "./ScanEventData";
import type { ScanPhase } from "./ScanPhase";

/**
 * 扫描 Channel 事件（envelope：operationId + 递增 sequence + RFC3339 at + kind + data）。
 */
export type LibraryScanEvent = { operationId: string, sequence: number, at: string, kind: ScanPhase, data: ScanEventData, };
