// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统一 Locator Wire 形式：`{ version: 1; kind: "..."; data: ... }`（契约 §22）。
 * serde 手写（tag+content 无法在顶层注入常量 version）；TS 类型覆盖为契约联合形状。
 */
export type LocatorDto = { version: 1, kind: "video", data: VideoLocatorDto } | { version: 1, kind: "book", data: BookLocatorDto } | { version: 1, kind: "pdf", data: PdfLocatorDto } | { version: 1, kind: "comic", data: ComicLocatorDto } | { version: 1, kind: "article", data: ArticleLocatorDto };
