// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Locator 类型投影（契约 §36.7；不含 Locator 明细）。
 */
export type LocatorKindDto = "video" | "book" | "pdf" | "comic" | "article";
