// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocatorDto } from "./LocatorDto";
import type { MarkerTypeDto } from "./MarkerTypeDto";

/**
 * `marker_create` 请求（契约 §23：标记中心）。
 */
export type MarkerCreateRequest = { mediaItemId: string, locator: LocatorDto, markerType: MarkerTypeDto, title: string | null, excerpt: string | null, note: string | null, };
