// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 标记类型（UI 统一叫"标记"，底层区分；契约 §42）。
 */
export type MarkerTypeDto = "bookmark" | "highlight" | "note" | "scene" | "quote" | "image";
