// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `marker_list_all` 请求（契约 §23.1 足迹聚合 Query）：列出所有未软删除标记。
 * `limit` 为 None 时由后端取默认上限。
 */
export type MarkerListAllRequest = { limit: number | null, };
