// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocatorDto } from "./LocatorDto";
import type { MarkerTypeDto } from "./MarkerTypeDto";

/**
 * 标记投影。
 */
export type MarkerDto = { markerId: string, mediaItemId: string, workId: string, editionId: string, locator: LocatorDto, markerType: MarkerTypeDto, title: string | null, excerpt: string | null, note: string | null, createdAt: string, updatedAt: string, };
