// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `marker_delete` 请求（契约 §23.2）：软删除（墓碑语义）。
 */
export type MarkerDeleteRequest = { markerId: string, };
