// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `marker_list` 请求（契约 §23.1）：列出某 MediaItem 下未软删除的标记。
 */
export type MarkerListRequest = { mediaItemId: string, };
