// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistorySummaryDto } from "./HistorySummaryDto";
import type { MediaStateProgressDto } from "./MediaStateProgressDto";

/**
 * Work 级用户状态聚合投影（schemaVersion 2，契约 §36.7）。
 * Application 层一次拼装 favorite/progress/history/marker 四表。
 */
export type MediaStateDto = { schemaVersion: 2, workId: string, favorite: boolean, progress: MediaStateProgressDto | null, historySummary: HistorySummaryDto | null, markerCount: number, 
/**
 * v0.2 预留位（§36.9）：恒为 null；未来豆瓣式五星时以契约修订落地。
 */
rating: null, };
