// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `media_state_get` 请求（契约 §36.7）。
 */
export type MediaStateGetRequest = { workId: string, };
