// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 媒介类型 Wire 值（与 domain MediaType 对齐）。
 */
export type MediaTypeDto = "movie" | "series" | "episode" | "book" | "document" | "comic" | "article" | "audio" | "unknown";
