// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaItemStatusDto } from "./MediaItemStatusDto";
import type { MediaTypeDto } from "./MediaTypeDto";
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

export type MediaItemSummaryDto = { mediaItemId: string, editionId: string, title: string, mediaType: MediaTypeDto, indexLabel: string, durationMs: number | null, pageCount: number | null, chapterCount: number | null, publishedAt: string | null, status: MediaItemStatusDto, availableResourceCount: number, 
/**
 * 季/集号投影（契约 §36.6）；无季集语义时为 null。后端从解析规则推导。
 */
seasonNumber: number | null, episodeNumber: number | null, progress: ProgressSummaryDto | null, primaryAction: PrimaryActionDto | null, };
