// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocatorKindDto } from "./LocatorKindDto";

/**
 * Work 级进度摘要投影。locatorKind 是类型投影，明细由 progress_recent 提供。
 */
export type MediaStateProgressDto = { editionId: string, mediaItemId: string, locatorKind: LocatorKindDto, updatedAt: string, };
