// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnrichmentStatusWire } from "./EnrichmentStatusWire";

/**
 * `metadata.changed` 事件负载（复用既有事件名；契约 §36.8）。
 * 只携带失效信号，完整投影由 Query 拉取。
 */
export type MetadataChangedDto = { schemaVersion: 1, at: string, operationId: string, sequence: number, workId: string, status: EnrichmentStatusWire, sourceId: string | null, error: string | null, };
