// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewLayoutDto } from "./OverviewLayoutDto";

/**
 * 总览布局读取结果。`revision` 为 `null` 表示从未保存过自定义布局，此时 `layout` 是
 * 领域默认布局；它与「保存了空布局」是两种不同事实。
 */
export type OverviewLayoutSnapshotDto = { layout: OverviewLayoutDto, revision: string | null, };
