// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewModulePlacementDto } from "./OverviewModulePlacementDto";

/**
 * 总览布局。空 `modules` 是合法的显式自定义（用户隐藏了全部模块），与「从未保存过」
 * 是两种不同事实（后者由 `revision` 为 `null` 表达）。
 */
export type OverviewLayoutDto = { schemaVersion: 1, modules: Array<OverviewModulePlacementDto>, };
