// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 总览布局重置请求（回到领域默认布局，删除已保存的自定义）。
 */
export type OverviewLayoutResetRequest = { expectedRevision: string | null, };
