// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 总览模块 ID（闭合集合）。
 *
 * 逐项写出 wire 值而不是用 `rename_all`：`reading-minutes` / `type-share` /
 * `reading-heatmap` 都是**连字符**，`snake_case` 会把它们悄悄改成下划线（那会变成
 * 另一个模块 ID，与 048 迁移的 CHECK 不再一致）。
 */
export type OverviewModuleIdDto = "preferences" | "metrics" | "reading-minutes" | "type-share" | "reading-heatmap";
