// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewModuleIdDto } from "./OverviewModuleIdDto";
import type { OverviewModuleSizeDto } from "./OverviewModuleSizeDto";

/**
 * 总览模块放置：模块、档位与三列网格的**起始格**坐标。
 */
export type OverviewModulePlacementDto = { module: OverviewModuleIdDto, size: OverviewModuleSizeDto, row: number, column: number, order: number, };
