// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 分页（契约 §11.3）。cursor 是 opaque string，前端不得解析。
 * NOTE-1：空值统一 `T | null`（字段始终存在）；`schemaVersion: 1` 契约要求。
 */
export type PageDto<T> = { 
/**
 * 契约字面量 `1`（C-04 修复：生成物为 `schemaVersion: 1`，禁止任意 number）。
 */
schemaVersion: 1, items: Array<T>, nextCursor: string | null, total: number | null, revision: string | null, };
