// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 页码区间。报刊页码允许非连续与不规则形态（`e12345`、`S1-S5`），
 * 因此保留来源文本而不是解析成整数；单页时 `end` 为 null。
 */
export type PageRangeDto = { start: string, end: string | null, };
