// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAnchorDto } from "./TextAnchorDto";

export type PdfLocatorDto = { pageIndex: number, x: number | null, y: number | null, zoom: number | null, textAnchor: TextAnchorDto | null, };
