// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodicalArticleDto } from "./PeriodicalArticleDto";

/**
 * 期刊期号；`label` 保留不规则期号原文（`3-4`、`Suppl 2`、`Spring`）。
 */
export type PeriodicalIssueDto = { id: string, volumeId: string, label: string | null, number: number | null, 
/**
 * 发行日期（来源精度：`YYYY` / `YYYY-MM` / `YYYY-MM-DD`）。
 */
publicationDate: string | null, ordinal: number, articles: Array<PeriodicalArticleDto>, };
