// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodicalIssueDto } from "./PeriodicalIssueDto";

/**
 * 期刊卷；`label` 保留来源原文（例如 `Suppl 1`），`number` 仅在可解析时存在。
 */
export type PeriodicalVolumeDto = { id: string, periodicalId: string, label: string | null, number: number | null, year: number | null, ordinal: number, issues: Array<PeriodicalIssueDto>, };
