// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 期刊身份与展示事实。`workId` 是期刊在 Haven 中的 Work 归属。
 */
export type PeriodicalDto = { id: string, workId: string, title: string, 
/**
 * ISSN（印刷版）；来源未给出时为 null，不与 electronic 互相推断。
 */
issnPrint: string | null, 
/**
 * ISSN（电子版）。
 */
issnElectronic: string | null, publisher: string | null, };
