// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeriodicalDto } from "./PeriodicalDto";
import type { PeriodicalVolumeDto } from "./PeriodicalVolumeDto";

/**
 * `periodical_tree_get` 响应：一个 Work 的完整期刊层级。
 *
 * 层级由后端按 Repository 顺序组装；前端只做渲染，不重排、不推断归属。
 */
export type PeriodicalTreeDto = { schemaVersion: 1, workId: string, periodical: PeriodicalDto, volumes: Array<PeriodicalVolumeDto>, };
