// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 文章正文可用性：Provider 对「这篇正文是否可读」的观察（闭合三态）。
 *
 * 这不是本地阅读能力：`fullText` 只说明来源声明有正文，`metadataOnly` 只说明
 * 来源只有元数据，`unknown` 说明没有观察到。页面据此区分三种情况，但**不得**
 * 用它阻止用户打开自己已经拥有的在线或离线内容。
 */
export type PeriodicalArticleAvailabilityDto = "full_text" | "metadata_only" | "unknown";
