// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `periodical_tree_get` 请求：按 Work 读取该作品的完整期刊层级。
 */
export type PeriodicalTreeGetRequest = { workId: string, };
