// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageRangeDto } from "./PageRangeDto";
import type { PeriodicalArticleAvailabilityDto } from "./PeriodicalArticleAvailabilityDto";

/**
 * 期刊文章。`mediaItemId` 绑定既有 MediaItem，阅读/进度/资源链路由既有契约承担。
 */
export type PeriodicalArticleDto = { id: string, issueId: string, mediaItemId: string, 
/**
 * 期内文章序号；来源未给出时为 null，后端不猜测。
 */
ordinal: number | null, title: string, 
/**
 * DOI 文本（不是可解析 URL）。
 */
doi: string | null, pageRange: PageRangeDto | null, 
/**
 * 来源 key（如 `europepmc`）与来源侧 opaque 文章 ID：只用于幂等与归属核对。
 */
sourceKey: string, remoteArticleId: string, 
/**
 * Provider 的正文观察。页面用它区分「仅有元数据」与「没有观察到」；
 * 真实可读路径由既有 Resource/Session 能力决定，不受此字段限制。
 */
availability: PeriodicalArticleAvailabilityDto, };
