// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceReadingContentWidthDto } from "./PreferenceReadingContentWidthDto";
import type { PreferenceReadingFontFamilyDto } from "./PreferenceReadingFontFamilyDto";
import type { PreferenceReadingFontSizeDto } from "./PreferenceReadingFontSizeDto";
import type { PreferenceReadingFontWeightDto } from "./PreferenceReadingFontWeightDto";
import type { PreferenceReadingLetterSpacingDto } from "./PreferenceReadingLetterSpacingDto";
import type { PreferenceReadingLineHeightDto } from "./PreferenceReadingLineHeightDto";
import type { PreferenceReadingPaginationDto } from "./PreferenceReadingPaginationDto";
import type { PreferenceReadingThemeDto } from "./PreferenceReadingThemeDto";

/**
 * 资源内设阅读部分更新。字段缺失表示不覆盖该字段；null 只用于清除整个 section。
 */
export type PreferenceReadingPatchDto = { fontFamily?: PreferenceReadingFontFamilyDto | null, customFontFamily?: string | null, fontSize?: PreferenceReadingFontSizeDto | null, lineHeight?: PreferenceReadingLineHeightDto | null, contentWidth?: PreferenceReadingContentWidthDto | null, theme?: PreferenceReadingThemeDto | null, customBackground?: string | null, customText?: string | null, fontWeight?: PreferenceReadingFontWeightDto | null, letterSpacing?: PreferenceReadingLetterSpacingDto | null, systemAuto?: boolean | null, pagination?: PreferenceReadingPaginationDto | null, };
