// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreferenceReadingThemeDto = "system" | "paper" | "warm" | "slate" | "dark" | "sepia" | "eyeCare" | "custom";
