// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资源内设的阅读字体。
 */
export type PreferenceReadingFontFamilyDto = "sans" | "serif" | "kai" | "heiti" | "fangsong" | "mianfei" | "custom";
