// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceComicPatchDto } from "./PreferenceComicPatchDto";
import type { PreferenceComicSettingsDto } from "./PreferenceComicSettingsDto";
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";
import type { PreferenceReadingSettingsDto } from "./PreferenceReadingSettingsDto";

/**
 * 资源内设读模型：同时返回原始覆盖和 effective 值，避免前端自行合并 global 设置。
 */
export type PreferenceGetResult = { schemaVersion: 1, mediaItemId: string, editionId: string, readingPatch: PreferenceReadingPatchDto | null, comicPatch: PreferenceComicPatchDto | null, editionReadingPatch: PreferenceReadingPatchDto | null, editionComicPatch: PreferenceComicPatchDto | null, mediaItemReadingPatch: PreferenceReadingPatchDto | null, mediaItemComicPatch: PreferenceComicPatchDto | null, effectiveReading: PreferenceReadingSettingsDto, effectiveComic: PreferenceComicSettingsDto, mediaItemRevision: string | null, editionRevision: string | null, };
