// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceComicDirectionDto } from "./PreferenceComicDirectionDto";
import type { PreferenceComicPageGapDto } from "./PreferenceComicPageGapDto";
import type { PreferenceComicPreloadPagesDto } from "./PreferenceComicPreloadPagesDto";
import type { PreferenceComicViewModeDto } from "./PreferenceComicViewModeDto";

/**
 * 有效漫画设置投影。`section` 是 Wire discriminator，Domain 设置本身不携带该字段。
 */
export type PreferenceComicSettingsDto = { section: "comic", viewMode: PreferenceComicViewModeDto, direction: PreferenceComicDirectionDto, pageGap: PreferenceComicPageGapDto, preloadPages: PreferenceComicPreloadPagesDto, };
