// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 读取资源内设的请求。`mediaItemId` 与 `editionId` 都必须由服务端验证归属。
 */
export type PreferenceGetRequest = { mediaItemId: string, editionId: string, };
