// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceComicPatchDto } from "./PreferenceComicPatchDto";
import type { PreferenceReadingPatchDto } from "./PreferenceReadingPatchDto";
import type { PreferenceTargetDto } from "./PreferenceTargetDto";

/**
 * 更新资源内设的请求；空 Patch（null）表示清除对应作用域的覆盖。
 */
export type PreferenceUpdateRequest = { mediaItemId: string, editionId: string, target: PreferenceTargetDto, readingPatch: PreferenceReadingPatchDto | null, comicPatch: PreferenceComicPatchDto | null, expectedRevision: string | null, };
