// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceReadingContentWidthDto } from "./PreferenceReadingContentWidthDto";
import type { PreferenceReadingFontFamilyDto } from "./PreferenceReadingFontFamilyDto";
import type { PreferenceReadingFontSizeDto } from "./PreferenceReadingFontSizeDto";
import type { PreferenceReadingFontWeightDto } from "./PreferenceReadingFontWeightDto";
import type { PreferenceReadingLetterSpacingDto } from "./PreferenceReadingLetterSpacingDto";
import type { PreferenceReadingLineHeightDto } from "./PreferenceReadingLineHeightDto";
import type { PreferenceReadingPaginationDto } from "./PreferenceReadingPaginationDto";
import type { PreferenceReadingThemeDto } from "./PreferenceReadingThemeDto";

/**
 * 有效阅读设置投影。`section` 是 Wire discriminator，Domain 设置本身不携带该字段。
 */
export type PreferenceReadingSettingsDto = { section: "reading", fontFamily: PreferenceReadingFontFamilyDto, customFontFamily: string | null, fontSize: PreferenceReadingFontSizeDto, lineHeight: PreferenceReadingLineHeightDto, contentWidth: PreferenceReadingContentWidthDto, theme: PreferenceReadingThemeDto, customBackground: string | null, customText: string | null, fontWeight: PreferenceReadingFontWeightDto, letterSpacing: PreferenceReadingLetterSpacingDto, systemAuto: boolean, pagination: PreferenceReadingPaginationDto, };
