// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 资源内设目标作用域（ADR-RESOURCE-PREF-001）。
 */
export type PreferenceTargetDto = "edition" | "media_item";
