// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceComicDirectionDto } from "./PreferenceComicDirectionDto";
import type { PreferenceComicPageGapDto } from "./PreferenceComicPageGapDto";
import type { PreferenceComicPreloadPagesDto } from "./PreferenceComicPreloadPagesDto";
import type { PreferenceComicViewModeDto } from "./PreferenceComicViewModeDto";

/**
 * 资源内设漫画部分更新。
 */
export type PreferenceComicPatchDto = { viewMode?: PreferenceComicViewModeDto | null, direction?: PreferenceComicDirectionDto | null, pageGap?: PreferenceComicPageGapDto | null, preloadPages?: PreferenceComicPreloadPagesDto | null, };
