// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreferenceGetResult } from "./PreferenceGetResult";
import type { PreferenceTargetDto } from "./PreferenceTargetDto";

/**
 * 更新结果，携带更新后的资源内设读模型和目标作用域 revision。
 */
export type PreferenceUpdateResult = { result: PreferenceGetResult, target: PreferenceTargetDto, revision: string | null, changed: boolean, };
