// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelHint } from "./LabelHint";
import type { LocatorDto } from "./LocatorDto";
import type { PrimaryActionKind } from "./PrimaryActionKind";

/**
 * 主操作。由后端基于进度、偏好和可用 Resource 决定（契约 §12 投影规则）。
 */
export type PrimaryActionDto = { kind: PrimaryActionKind, labelHint: LabelHint, editionId: string, mediaItemId: string | null, locator: LocatorDto | null, };
