// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 主操作类型。
 */
export type PrimaryActionKind = "playback" | "reader" | "comic" | "article" | "open_edition";
