// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `progress_save` 结果：新 Revision（opaque；语义由 BE-REVISION-001 正式化）。
 */
export type ProgressSaveResult = { revision: string, };
