// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `progress_recent` 请求（契约 §23.1）：最近活跃进度（首页 Continue 数据源）。
 */
export type ProgressRecentRequest = { limit: number | null, };
