// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionWire } from "./CompletionWire";
import type { LocatorDto } from "./LocatorDto";

/**
 * 进度摘要（progressRatio 是派生值，事实来源是 locator）。
 */
export type ProgressSummaryDto = { mediaItemId: string, completion: CompletionWire, progressRatio: number | null, 
/**
 * 进度写入的 opaque CAS token。与 `ProgressSaveResult.revision` 同源；
 * `updatedAt` 仅用于展示，不能被前端当作并发写入版本。
 */
revision: string, updatedAt: string, locator: LocatorDto, 
/**
 * 关键帧（退出时截取的当前帧，data URI 或 haven-resource 链接），缺失回退海报。
 */
keyframeUri?: string, };
