// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionWire } from "./CompletionWire";
import type { LocatorDto } from "./LocatorDto";

/**
 * `progress_save` 请求（契约 §22.6）。
 * workId/editionId 由后端从 MediaItem 推导，前端禁止提交（防 ID 矛盾）。
 */
export type ProgressSaveRequest = { mediaItemId: string, locator: LocatorDto, completion: CompletionWire | null, expectedRevision: string | null, 
/**
 * 关键帧 JPEG data URL（data:image/jpeg;base64,...），可选，超大则忽略。
 */
keyframe?: string, };
