// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `progress_reset` 请求（契约 §23.2）：业务操作，只清进度状态不删除实体。
 */
export type ProgressResetRequest = { mediaItemId: string, };
