// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocatorDto } from "./LocatorDto";

/**
 * `progress_mark_completed` 请求。`initial_locator` 只用于尚无 Progress
 * 时创建安全起点；已有记录时后端原子保留其 Locator 与 percentage。
 */
export type ProgressMarkCompletedRequest = { mediaItemId: string, initialLocator: LocatorDto, };
