// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 查询分类 = `all` | ContentCategory（契约 §12）。
 */
export type QueryCategory = "all" | "video" | "book" | "comic" | "periodical";
