// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadingSessionCategoryDto } from "./ReadingSessionCategoryDto";

/**
 * 分类时长合计（只出现在真的有时长的分类上）。
 */
export type ReadingCategoryTotalDto = { category: ReadingSessionCategoryDto, durationMs: number, };
