// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadingCategoryTotalDto } from "./ReadingCategoryTotalDto";
import type { ReadingDailyBucketDto } from "./ReadingDailyBucketDto";
import type { ReadingHeatmapCellDto } from "./ReadingHeatmapCellDto";
import type { ReadingOverviewRangeDto } from "./ReadingOverviewRangeDto";

/**
 * 总览聚合结果。
 *
 * 所有字段都是对已持久化会话事实的求和或由它直接导出的结论；没有任何记录时
 * `sessionCount == 0` 且可选统计量保持 `null`（不是 0）。
 */
export type ReadingOverviewDto = { schemaVersion: 1, range: ReadingOverviewRangeDto, sessionCount: number, totalDurationMs: number, daily: Array<ReadingDailyBucketDto>, categories: Array<ReadingCategoryTotalDto>, heatmapCells: Array<ReadingHeatmapCellDto>, 
/**
 * 高峰时段的起点（本地小时）；窗口内没有任何记录时为 `null`。
 */
peakStartHour: number | null, 
/**
 * 高峰时段的右端点（= 起点 + 1，可能为 24）；无记录时为 `null`。
 */
peakEndHour: number | null, 
/**
 * 窗口内最长的连续活跃阅读天数；无记录时为 `null`。
 */
longestStreakDays: number | null, averageDailyDurationMs: number | null, recentWeekDurationMs: number | null, };
