// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TocItemDto } from "./TocItemDto";

/**
 * `reader_toc_get` 响应。非 EPUB 图书（TXT/Markdown）返回 FORMAT_UNSUPPORTED，
 * EPUB 无显式目录时按 spine 顺序生成扁平兜底目录。
 */
export type ReaderTocResultDto = { schemaVersion: 1, sessionId: string, items: Array<TocItemDto>, };
