// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 统计窗口：按请求的 UTC 偏移换算出的本地日期闭区间。
 */
export type ReadingOverviewRangeDto = { startLocalDate: string, endLocalDate: string, days: number, utcOffsetMinutes: number, };
