// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaderSearchEventData } from "./ReaderSearchEventData";
import type { ReaderSearchEventKind } from "./ReaderSearchEventKind";

/**
 * `reader_search` Channel 事件（与 `search.source` 同 envelope 语义）。
 */
export type ReaderSearchEvent = { operationId: string, sequence: number, at: string, kind: ReaderSearchEventKind, data: ReaderSearchEventData, };
