// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaderSearchHitDto } from "./ReaderSearchHitDto";

/**
 * `reader_search` Channel 事件负载。
 */
export type ReaderSearchEventData = { hits: Array<ReaderSearchHitDto>, scannedChapters: number | null, totalChapters: number | null, code: string | null, message: string | null, };
