// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `reader_toc_get` 的只读请求。MediaItem/Resource/Engine 均从 Session 推导。
 */
export type ReaderTocGetRequest = { sessionId: string, };
