// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 总览读取请求：窗口天数 + 显式 UTC 偏移（分钟）。
 *
 * 偏移由调用方显式给出，而不是后端读运行环境时区：同一份事实在任何机器上都聚合出
 * 同一份结果，「某个会话属于哪一天/哪个小时」这种边界也就可复现、可测试。
 */
export type ReadingOverviewGetRequest = { days: number, utcOffsetMinutes: number, };
