// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个本地日的时长（窗口内每一天一条，含未阅读的空日）。
 */
export type ReadingDailyBucketDto = { localDate: string, 
/**
 * ISO 星期序号：1 = 周一 … 7 = 周日。
 */
weekday: number, durationMs: number, };
