// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaderSearchHitDto } from "./ReaderSearchHitDto";

/**
 * `reader_search` 响应。命中为原文片段（exact 12..240，prefix/suffix 各 30）。
 */
export type ReaderSearchResultDto = { schemaVersion: 1, sessionId: string, hits: Array<ReaderSearchHitDto>, };
