// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 热力图格子（只出现在真的有时长的「星期 × 小时」上）。
 */
export type ReadingHeatmapCellDto = { 
/**
 * ISO 星期序号：1 = 周一 … 7 = 周日。
 */
weekday: number, 
/**
 * 本地小时 0..=23。
 */
hour: number, durationMs: number, };
