// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAnchorDto } from "./TextAnchorDto";

/**
 * 检索命中（`book-search.ts` 前端语义的 Rust 等价物；按 TF-IDF 分数降序）。
 */
export type ReaderSearchHitDto = { chapterId: string, chapterTitle: string, chapterIndex: number, paragraphIndex: number, progressionInChapter: number, textAnchor: TextAnchorDto, score: number, };
