// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话归属的一级分类（无 `all`：一次真实会话必然属于某一类）。
 */
export type ReadingSessionCategoryDto = "video" | "book" | "comic" | "periodical";
