// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `reader_search` 请求。query 1..128 字符（归一化后），空或超长返回空结果。
 */
export type ReaderSearchRequest = { sessionId: string, query: string, };
