// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `reader_search` Channel 事件种类（`ReaderSearch` 单书检索，terminal 唯一）。
 */
export type ReaderSearchEventKind = "started" | "progress" | "result" | "completed" | "cancelled" | "failed";
