// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource 类型的安全 Wire 值。定位内容（本地路径、远程 URL、凭据）永不出现在 DTO。
 */
export type ResourceTypeDto = "local_file" | "cloud_file" | "http_file" | "video_stream" | "hls_stream" | "dash_stream" | "publication_file" | "comic_archive" | "image_sequence" | "article_snapshot" | "remote_chapter" | "remote_page_set" | "remote_stream";
