// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceSummaryDto } from "./ResourceSummaryDto";

export type ResourceListDto = { schemaVersion: 1, items: Array<ResourceSummaryDto>, };
