// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailabilityDto } from "./AvailabilityDto";
import type { ResourceTypeDto } from "./ResourceTypeDto";
import type { StreamKindDto } from "./StreamKindDto";

/**
 * `resource_list_by_media_item` 的安全摘要。
 * 该类型明确不包含 locator、root path、下载 URL、签名 URL 或 credential ref。
 */
export type ResourceSummaryDto = { resourceId: string, resourceType: ResourceTypeDto, availability: AvailabilityDto, mimeType: string | null, size: number | null, storageDisplayName: string | null, sourceDisplayName: string | null, isOffline: boolean, isLocal: boolean, requiresReauthorization: boolean, 
/**
 * 在线流种类（契约 §36.4）；仅 remote_stream 资源非 null，其余恒 null。
 */
streamKind: StreamKindDto | null, };
