// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 扫描阶段（契约 §14.4）。
 */
export type ScanPhase = "started" | "enumerating" | "detecting" | "fingerprinting" | "indexing" | "item_indexed" | "warning" | "completed" | "cancelled" | "failed";
