// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

/**
 * `scan_cancel` 幂等结果。运行中任务返回 cancelled 受理；
 * 已终态任务返回真实终态。
 */
export type ScanCancelResultDto = { taskId: string, alreadyTerminal: boolean, phase: ScanPhase, };
