// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `library_scan_start` 成功响应（R-C02 冻结裁决：**幂等**——同一 storageLocationId
 * 已有运行任务时，返回既有任务而非冲突错误；前端按 taskId 合并订阅）。
 */
export type ScanStartResult = { schemaVersion: 1, operationId: string, taskId: string, 
/**
 * true = 该任务已在运行，本次启动幂等合并到既有任务。
 */
alreadyRunning: boolean, };
