// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 扫描 Channel 事件负载（稳定 taskId、阶段、计数、当前项与终态）。
 */
export type ScanEventData = { taskId: string, filesSeen: number, recognized: number, new: number, updated: number, skipped: number, errors: number, currentItem: string | null, message: string | null, };
