// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_history_record` 请求。显式写命令避免 Query 隐式写数据库。
 */
export type SearchHistoryRecordRequest = { term: string, };
