// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryCategory } from "./QueryCategory";

/**
 * 渐进式来源搜索请求（契约 §36.3）。query 去空白后为空 → INVALID_ARGUMENT。
 */
export type SearchSourceStartRequest = { query: string, 
/**
 * null = 全部分类。
 */
category: QueryCategory | null, 
/**
 * null = 后端默认上限；>50 → INVALID_ARGUMENT。
 */
limitPerSource: number | null, };
