// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_source_cancel` 幂等结果；已终态任务返回真实状态。
 */
export type SearchSourceCancelResultDto = { operationId: string, alreadyTerminal: boolean, };
