// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkCardDto } from "./WorkCardDto";

/**
 * 搜索 Channel 事件负载。sourceId 仅 source_result/warning 非空；
 * works 仅 source_result 非空；code 仅 warning/failed 非空。
 */
export type SearchSourceEventData = { sourceId: string | null, works: Array<WorkCardDto>, 
/**
 * warning/failed 携带稳定错误码（v1 Error Catalog），其余 null。
 */
code: string | null, 
/**
 * warning 携带安全用户文案（不含完整 URL/路径/Provider Body），其余 null
 * （V2-H 收尾批次；来源健康度明细）。
 */
message: string | null, };
