// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_history_list` 请求；None 使用应用层默认上限。
 */
export type SearchHistoryListRequest = { limit: number | null, };
