// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_source_start` 成功响应（R-C02 同款幂等语义：alreadyRunning 合并既有任务）。
 */
export type SearchStartResultDto = { operationId: string, taskId: string, alreadyRunning: boolean, };
