// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_source_cancel` 请求（幂等；未知 operationId → RESOURCE_NOT_FOUND）。
 */
export type SearchSourceCancelRequest = { operationId: string, };
