// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `search_history_remove` 请求。
 */
export type SearchHistoryRemoveRequest = { term: string, };
