// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 搜索 Channel 事件种类（契约 §36.3）。Terminal 只能出现一次：
 * completed | cancelled | failed。
 */
export type SearchSourceEventKind = "started" | "source_result" | "warning" | "completed" | "cancelled" | "failed";
