// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSourceEventData } from "./SearchSourceEventData";
import type { SearchSourceEventKind } from "./SearchSourceEventKind";

/**
 * `search.source` Channel 事件（envelope 与 §10.3 一致；sequence 从 1 严格递增）。
 */
export type SearchSourceEvent = { operationId: string, sequence: number, at: string, kind: SearchSourceEventKind, data: SearchSourceEventData, };
