// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 搜索历史条目（V02-SETTINGS-PRIVACY-DATA-007）。
 */
export type SearchHistoryEntryDto = { term: string, lastUsedAt: string, };
