// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session_open` 的执行引擎。Wire 值是稳定的 opaque 枚举，不暴露实现类型。
 */
export type SessionEngineDto = "playback" | "reader" | "comic" | "article";
