// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 关闭消费 Session 的结果（未知/重复 token 也返回成功）。
 */
export type SessionCloseResultDto = { schemaVersion: 1, closed: boolean, };
