// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionEngineDto } from "./SessionEngineDto";

/**
 * 打开消费 Session 的请求。
 */
export type SessionOpenRequest = { mediaItemId: string, engine: SessionEngineDto, };
