// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressSummaryDto } from "./ProgressSummaryDto";
import type { SessionEngineDto } from "./SessionEngineDto";

/**
 * 打开消费 Session 的安全响应。受控内容 URI 由 Tauri registry 签发。
 */
export type SessionOpenResultDto = { schemaVersion: 1, sessionId: string, 
/**
 * Comic 会话必须返回 null，防止整本 CBZ 绕过逐页授权；其他引擎返回受控 URI。
 */
contentUri: string | null, workId: string, editionId: string, mediaItemId: string, engine: SessionEngineDto, progress: ProgressSummaryDto | null, };
