// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryListRequest } from "./LibraryListRequest";
import type { WorkCardDto } from "./WorkCardDto";

/**
 * 内容架（`home_get` / `library_shelves`；NOTE-7 契约定义）。
 */
export type ShelfDto = { shelfId: string, titleKey: string, preview: Array<WorkCardDto>, viewMore: LibraryListRequest | null, };
