// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_work_import` 请求：导入搜索候选（operationId + 序号定位服务端缓存）。
 */
export type SourceWorkImportRequest = { operationId: string, index: number, };
