// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_add` 结果：返回稳定 sourceId（`custom_` 前缀），端点不出 IPC。
 */
export type SourceAddResult = { schemaVersion: 1, sourceId: string, };
