// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_registry_set` 请求（幂等；未知 sourceId → INVALID_ARGUMENT）。
 */
export type SourceRegistrySetRequest = { sourceId: string, enabled: boolean, };
