// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_work_import` 结果：入库后的真实身份（可路由播放）。
 */
export type SourceWorkImportResult = { schemaVersion: 1, workId: string, 
/**
 * 首个可消费媒体条目（直接可用于 session/stream open）。
 */
mediaItemId: string, };
