// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 来源配置边界：一个入口可聚合多个上游，或一个入口对应一个 Provider/目录。
 */
export type SourceModeDto = "single" | "collection";
