// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_remove`：删除自定义源（ADR-001 删除顺序：先删系统凭据再清持久化引用）。
 */
export type SourceRemoveRequest = { sourceId: string, };
