// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceDescriptorDto } from "./SourceDescriptorDto";

/**
 * `source_registry_list` 顶层响应（schemaVersion 2，契约 §36.2）。
 */
export type SourceRegistryDto = { schemaVersion: 2, 
/**
 * 内置目录固定非空集合；空目录返回 []。
 */
sources: Array<SourceDescriptorDto>, };
