// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_registry_set` 结果（重复设置同值返回同结果）。
 */
export type SourceRegistrySetResult = { sourceId: string, enabled: boolean, };
