// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_update`：修改自定义源显示名与/或端点。null = 不变。
 */
export type SourceUpdateRequest = { sourceId: string, displayName: string | null, 
/**
 * null = 不变；空串非法（用 `source_registry_set_endpoint` 语义清空不适用，此处必须给出有效端点）。
 */
endpoint: string | null, };
