// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_add`：新增自定义 OPDS 书源（V2-H 收尾批次）。
 * 凭据不随本请求提交；先 add 再 `source_set_credential`（secret 单独走 keyring）。
 */
export type SourceAddRequest = { displayName: string, 
/**
 * OPDS 根目录 URL（http/https 绝对地址）；响应不含端点本身。
 */
endpoint: string, };
