// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_add`：新增自定义来源（V2-H 收尾批次；Task 1 增补 kind；Task 2 增补
 * 自托管漫画库）。凭据不随本请求提交；先 add 再 `source_set_credential`
 * （secret 单独走 keyring）。
 * RSS/Atom 订阅源不接受凭据，端点必须使用 HTTPS 且不能带查询串；
 * Komga/Kavita 端点同样必须使用 HTTPS 且不能带查询串，API key 只经请求头注入。
 */
export type SourceAddRequest = { displayName: string, 
/**
 * OPDS 根目录 URL（http/https 绝对地址）、RSS/Atom 订阅源地址或 Komga/
 * Kavita 漫画库地址（后两者仅 https，不含查询串）；响应不含端点本身。
 */
endpoint: string, 
/**
 * 来源种类；缺省为 `opds`，与新增该字段之前的请求保持向后兼容。
 */
kind?: "opds" | "feed" | "komga" | "kavita", };
