// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_registry_set_endpoint` 请求（V2-B 实战批次增量；契约 §36.2 演进）。
 * 端点只写后端持久化（settings KV），永不回传 IPC。
 */
export type SourceEndpointSetRequest = { sourceId: string, 
/**
 * 仅接受 http/https 绝对 URL；写入前校验，响应不含端点本身。
 */
endpoint: string, };
