// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 来源面向用户的内容分类。该分类只用于设置页分组和来源筛选，
 * 不替代搜索/媒体领域中的 `ContentCategory`。
 */
export type SourceCategoryDto = "video" | "book" | "comic" | "periodical";
