// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_update` 幂等结果。
 */
export type SourceUpdateResult = { schemaVersion: 1, sourceId: string, };
