// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_registry_set_endpoint` 结果。
 */
export type SourceEndpointSetResult = { sourceId: string, endpointConfigured: boolean, };
