// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 来源健康（后端探测事实；出厂 unknown，契约 §36.2）。
 */
export type SourceHealthDto = "unknown" | "ok" | "degraded" | "down";
