// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 来源能力种类（capability 投影；契约 §36.2）。
 */
export type SourceKindDto = "metadata" | "stream" | "download";
