// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_remove` 幂等结果。
 */
export type SourceRemoveResult = { schemaVersion: 1, sourceId: string, 
/**
 * true = 系统凭据实际删除；false = 本无凭据或已不存在。
 */
credentialDeleted: boolean, };
