// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `source_set_credential`：写入/清除自定义源凭据。secret 只进系统 keyring；
 * 持久化仅存 credential_ref；secret 与 target 禁止出 IPC、日志。
 */
export type SourceSetCredentialRequest = { sourceId: string, 
/**
 * null = 清除凭据；Some(空串) 非法 → INVALID_ARGUMENT。
 */
secret: string | null, };
