// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceCategoryDto } from "./SourceCategoryDto";
import type { SourceHealthDto } from "./SourceHealthDto";
import type { SourceKindDto } from "./SourceKindDto";
import type { SourceModeDto } from "./SourceModeDto";

/**
 * 来源描述符。端点 URL、凭据与端点内容禁止进入本投影（契约 §36.2）。
 */
export type SourceDescriptorDto = { 
/**
 * 稳定来源 ID（内置静态目录定义，前端不得自造）。
 */
sourceId: string, 
/**
 * 安全显示名。
 */
displayName: string, kinds: Array<SourceKindDto>, 
/**
 * 面向用户的内容分类（影视、图书、漫画、报刊文章）。
 */
categories: Array<SourceCategoryDto>, 
/**
 * 单一来源或聚合来源。
 */
mode: SourceModeDto, 
/**
 * 由内置来源清单维护的说明；自定义来源使用固定安全文案。
 */
notes: string, enabled: boolean, health: SourceHealthDto, 
/**
 * 用户自填端点（CMS10/M3U）是否已配置；端点本身不出 IPC。
 */
endpointConfigured: boolean, 
/**
 * 健康探测：最后检测时间（RFC3339），无探测为 null。
 */
lastChecked: string | null, 
/**
 * 最后一次探测延迟（毫秒），无探测为 null。
 */
latencyMs: number | null, 
/**
 * 滚动成功率（0.0-1.0），无数据为 null。
 */
successRate: number | null, };
