// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageProviderTypeDto } from "./StorageProviderTypeDto";
import type { StorageStatusDto } from "./StorageStatusDto";

/**
 * `storage_location_list` 的安全行投影。
 *
 * 只允许传输位置的稳定标识、显示名、provider 和状态；不得把 rootRef/rootPath、
 * credentialRef、绝对路径、UNC 路径或其他内部路径带出特权后端边界。
 */
export type StorageLocationDto = { locationId: string, displayName: string, providerType: StorageProviderTypeDto, status: StorageStatusDto, };
