// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 存储位置状态 Wire 枚举。
 */
export type StorageStatusDto = "connected" | "disconnected" | "auth_expired" | "unavailable" | "read_only" | "error" | "disabled" | "missing";
