// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `library_scan_start` 请求（C-06 冻结裁决）。
 * 生产协议**只提交已注册的 `storageLocationId`**，不暴露裸 rootPath：
 * 任意路径能力与"禁止向高权限 WebView 暴露本地路径"的安全边界冲突。
 * 存储提供方 Wire 枚举（与 domain 值对齐，但 Domain Entity 不出 IPC）。
 */
export type StorageProviderTypeDto = "local" | "web_dav" | "one_drive" | "google_drive";
