// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 在线流种类（契约 §36.4）；仅 remote_stream 资源非 null。
 */
export type StreamKindDto = "hls" | "direct";
