// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 字幕格式是受控的解析提示，不是文件名或路径。
 */
export type SubtitleFormatDto = "srt" | "vtt" | "sbv" | "ass" | "ssa" | "ttml" | "dfxp" | "sub" | "lrc" | "unknown";
