// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleFormatDto } from "./SubtitleFormatDto";

/**
 * Session 内可消费的字幕轨道。路径、来源 URL 和凭据永不进入 Wire。
 */
export type SubtitleTrackDto = { trackId: string, label: string, language: string | null, format: SubtitleFormatDto, contentUri: string, };
