// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextAnchorDto = { exact: string | null, prefix: string | null, suffix: string | null, };
