// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Third-party notice 的最小可读投影；完整正文仍由构建时登记的仓库清单拥有。
 */
export type ThirdPartyNoticeDto = { name: string, license: string, };
