// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目录条目（扁平列表，depth 决定层级；前端按 depth 缩进渲染）。
 * id 为稳定 `FNV-1a64(href \0 title \0 occurrence)` 的 16 位 hex，
 * 同文件跨会话一致，可用于书签/批注的章节归属比对。
 */
export type TocItemDto = { id: string, title: string, depth: number, 
/**
 * 可选的 EPUB 文档内锚点。解析失败或条目指向章节起点时为 null。
 */
fragment?: string, 
/**
 * 0..1；条目所在 spine 文档起点在全书的估算进度（spine 序号 / spine 长度）。
 */
progression: number, };
