// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 热榜单项投影。生产海报只能走受控 `haven://artwork/*` 代理；缺失时为 null。
 */
export type TrendingItemDto = { title: string, subtitle: string, description: string, 
/**
 * 受控海报 URI（`haven://artwork/<id>`）；为 null 时前端用本地占位。
 */
posterUri: string | null, statusBadge: string | null, };
