// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendingItemDto } from "./TrendingItemDto";

/**
 * 热榜看板投影（4 榜：动漫/国产剧/综艺/英美剧）。
 */
export type TrendingBoardDto = { boardId: string, title: string, subtitle: string, items: Array<TrendingItemDto>, };
