// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendingBoardDto } from "./TrendingBoardDto";

/**
 * `trending_boards_get` 响应（schemaVersion 1，空榜返回 []）。
 */
export type TrendingBoardsDto = { schemaVersion: 1, boards: Array<TrendingBoardDto>, };
