// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tvbox_config_preview` 请求：待预览的配置地址。
 *
 * 请求里只有用户输入的地址本身，没有 header、凭据或保存意图。
 */
export type TvboxConfigPreviewRequest = { url: string, };
