// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TvboxConfigImplementationKindDto } from "./TvboxConfigImplementationKindDto";

/**
 * `tvbox_config_preview` 响应：配置的**形态摘要**。
 *
 * 只含计数、形态分类、固定白名单字段名与第三方实现种类；不含配置地址、原始 JSON、
 * 站点端点、header 值、`ext` 内容、Cookie、Token 或任何凭据。数字 `type` 的语义
 * **不做解释**：站点分类只依据 `api` 的形态，未确认的形态只计入
 * `unclassifiedSiteCount`，不声明支持也不声明不支持。
 */
export type TvboxConfigPreviewDto = { schemaVersion: 1, siteCount: number, liveCount: number, parserCount: number, skippedSiteRows: number, skippedLiveRows: number, skippedParserRows: number, spiderConfigured: boolean, spiderKind: TvboxConfigImplementationKindDto | null, spiderHasIntegrityDigest: boolean, 
/**
 * `api` 是 http(s) 端点的站点数（协议细节本轮不判定）。
 */
httpEndpointSiteCount: number, 
/**
 * `api` 使用 spider 协议前缀的站点数（运行需要第三方代码，本轮不执行）。
 */
spiderSiteCount: number, 
/**
 * 证据不足、无法从形态归类的站点数。保留原文，不猜语义。
 */
unclassifiedSiteCount: number, 
/**
 * 已识别但本轮未结构化的顶层字段名（`wallpaper` / `rules` / `flags` / `doh` /
 * `ads` / `logo` / `epg` / `danmaku` 的固定白名单子集）。
 */
opaqueTopLevelFieldNames: Array<string>, 
/**
 * 未识别顶层字段的**条数**；字段名与取值都不回传。
 */
unrecognizedTopLevelFieldCount: number, 
/**
 * 因条数上限被丢弃的顶层字段数（不静默：调用方能看到有东西没被保留）。
 */
withheldTopLevelFieldCount: number, };
