// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `tvbox_config_save` 请求：用户为一份 TVBox / FongMi 配置起的显示名与配置地址。
 *
 * 请求里只有用户输入：没有 header、没有凭据，也没有任何配置内容。地址可能带访问
 * 令牌，因此它只出现在请求方向上，响应里没有它。
 */
export type TvboxConfigSaveRequest = { displayName: string, url: string, };
