// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 配置声明的第三方实现种类（闭合集合）。
 *
 * 识别到即代表「运行需要第三方代码」；本切片只标记，不下载、不加载、不执行。
 */
export type TvboxConfigImplementationKindDto = "jar" | "javascript" | "python" | "json_manifest" | "unidentified";
