// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TvboxConfigPreviewDto } from "./TvboxConfigPreviewDto";

/**
 * `tvbox_config_save` 响应：稳定来源 ID + 配置的**形态摘要**。
 *
 * 摘要与 `tvbox_config_preview` 响应是同一个形状：不含配置地址、原始 JSON、站点
 * 端点、header 值、`ext` 内容、Cookie、Token 或任何凭据。来源被登记后**默认停用**，
 * 启用状态由来源注册表持有，本响应不重复声明。
 */
export type TvboxConfigSaveResult = { schemaVersion: 1, 
/**
 * 由来源注册表生成的稳定 `custom_tvbox_` 前缀 sourceId。
 */
sourceId: string, preview: TvboxConfigPreviewDto, };
