// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `video_screenshot_begin` 返回的有界上传能力；不包含路径或图片数据。
 */
export type VideoScreenshotBeginResultDto = { schemaVersion: 1, uploadId: string, maxChunkBytes: number, maxTotalBytes: number, };
