// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 用户关闭保存对话框时以 `cancelled` 结果返回，不作为错误。
 */
export type VideoScreenshotStatusDto = "saved" | "cancelled";
