// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个截图分块。Command/Application 会再次校验大小、归属和 sequence。
 */
export type VideoScreenshotChunkRequest = { uploadId: string, sequence: number, bytes: Array<number>, };
