// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentCategory } from "./ContentCategory";
import type { ExternalIdDto } from "./ExternalIdDto";
import type { MediaTypeDto } from "./MediaTypeDto";
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";
import type { WorkDetailCountsDto } from "./WorkDetailCountsDto";

export type WorkDetailHeaderDto = { schemaVersion: 1, workId: string, title: string, originalTitle: string | null, description: string | null, posterUri: string | null, backdropUri: string | null, releaseYear: number | null, director?: string, actor?: string, categories: Array<ContentCategory>, availableMediaTypes: Array<MediaTypeDto>, favorite: boolean, primaryAction: PrimaryActionDto | null, progress: ProgressSummaryDto | null, 
/**
 * 元数据去重键投影（契约 §36.1）；无已知映射返回 []。
 */
externalIds: Array<ExternalIdDto>, counts: WorkDetailCountsDto, };
