// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkDetailCountsDto = { editions: number, relations: number, availableResources: number, activeDownloads: number, markers: number, };
