// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentCategory } from "./ContentCategory";
import type { ExternalIdDto } from "./ExternalIdDto";
import type { MediaTypeDto } from "./MediaTypeDto";
import type { PrimaryActionDto } from "./PrimaryActionDto";
import type { ProgressSummaryDto } from "./ProgressSummaryDto";

/**
 * 作品卡片投影（Library 列表 / 搜索结果共用）。
 */
export type WorkCardDto = { workId: string, title: string, originalTitle: string | null, description: string | null, categories: Array<ContentCategory>, availableMediaTypes: Array<MediaTypeDto>, posterUri: string | null, backdropUri: string | null, releaseYear: number | null, ratingValue: number | null, ratingScale: number | null, favorite: boolean, progress: ProgressSummaryDto | null, primaryAction: PrimaryActionDto | null, 
/**
 * 元数据去重键投影（契约 §36.1）；无已知映射返回 []。
 */
externalIds: Array<ExternalIdDto>, };
