//! TypeScript Binding 生成（IPC-WIRE-001 核心：单一事实源、生成物可复现）。
//!
//! `generate_wire_bindings()` 是纯函数：同一 Rust 源码 → 同一 TS 输出。
//! - `examples/gen_wire_bindings.rs` 调用它写盘（`前端/app/src/lib/ipc/generated/wire.ts`）。
//! - 一致性测试（`tests/wire_bindings_consistency.rs`）比对生成结果与 checked-in 文件，
//!   防止生成物漂移（wire.ts 与 Rust 源不一致时测试失败）。

use ts_rs::{Config, TS};

use super::cloud_storage::*;
use super::dto::*;

/// 生成完整 wire.ts 内容（不含文件 IO）。
pub fn generate_wire_bindings() -> String {
    let config = Config::default();
    let mut out = String::new();
    out.push_str(
        "// Generated by haven-application/examples/gen_wire_bindings.rs (IPC-WIRE-001)\n",
    );
    out.push_str("// 单一事实源: 后端/crates/haven-application/src/wire/ — 禁止手改。\n");
    out.push_str("// 契约: plan/FRONTEND_BACKEND_CONTRACT.md §11–§12、§22。\n\n");

    // TypeScript interface 支持前向引用，声明顺序无关紧要。
    // 单文件导出：过滤 ts-rs 为多文件模式生成的 `import type` 行（同文件内类型互相可见）。
    for declaration in [
        ContentCategory::export_to_string(&config).unwrap(),
        QueryCategory::export_to_string(&config).unwrap(),
        MediaTypeDto::export_to_string(&config).unwrap(),
        CompletionWire::export_to_string(&config).unwrap(),
        PrimaryActionKind::export_to_string(&config).unwrap(),
        LabelHint::export_to_string(&config).unwrap(),
        PrimaryActionDto::export_to_string(&config).unwrap(),
        WorkCardDto::export_to_string(&config).unwrap(),
        ProgressSummaryDto::export_to_string(&config).unwrap(),
        LocatorDto::export_to_string(&config).unwrap(),
        VideoLocatorDto::export_to_string(&config).unwrap(),
        BookLocatorDto::export_to_string(&config).unwrap(),
        PdfLocatorDto::export_to_string(&config).unwrap(),
        ComicLocatorDto::export_to_string(&config).unwrap(),
        ArticleLocatorDto::export_to_string(&config).unwrap(),
        TextAnchorDto::export_to_string(&config).unwrap(),
        PageDto::<WorkCardDto>::export_to_string(&config).unwrap(),
        LibraryListSort::export_to_string(&config).unwrap(),
        LibraryListRequest::export_to_string(&config).unwrap(),
        SessionEngineDto::export_to_string(&config).unwrap(),
        SessionOpenRequest::export_to_string(&config).unwrap(),
        SubtitleFormatDto::export_to_string(&config).unwrap(),
        SubtitleTrackDto::export_to_string(&config).unwrap(),
        SessionOpenResultDto::export_to_string(&config).unwrap(),
        SessionCloseRequest::export_to_string(&config).unwrap(),
        SessionCloseResultDto::export_to_string(&config).unwrap(),
        ComicPageManifestGetRequest::export_to_string(&config).unwrap(),
        ComicPageAvailabilityDto::export_to_string(&config).unwrap(),
        ComicPageDto::export_to_string(&config).unwrap(),
        ComicPageManifestDto::export_to_string(&config).unwrap(),
        FavoriteSetRequest::export_to_string(&config).unwrap(),
        FavoriteSetResult::export_to_string(&config).unwrap(),
        ProgressSaveRequest::export_to_string(&config).unwrap(),
        ProgressMarkCompletedRequest::export_to_string(&config).unwrap(),
        ProgressSaveResult::export_to_string(&config).unwrap(),
        HistoryEntryDto::export_to_string(&config).unwrap(),
        HistoryListRequest::export_to_string(&config).unwrap(),
        SearchHistoryEntryDto::export_to_string(&config).unwrap(),
        SearchHistoryListRequest::export_to_string(&config).unwrap(),
        SearchHistoryRecordRequest::export_to_string(&config).unwrap(),
        SearchHistoryRemoveRequest::export_to_string(&config).unwrap(),
        ProgressRecentRequest::export_to_string(&config).unwrap(),
        ProgressResetRequest::export_to_string(&config).unwrap(),
        MarkerTypeDto::export_to_string(&config).unwrap(),
        MarkerCreateRequest::export_to_string(&config).unwrap(),
        MarkerDto::export_to_string(&config).unwrap(),
        MarkerListRequest::export_to_string(&config).unwrap(),
        MarkerListAllRequest::export_to_string(&config).unwrap(),
        MarkerDeleteRequest::export_to_string(&config).unwrap(),
        StorageProviderTypeDto::export_to_string(&config).unwrap(),
        StorageStatusDto::export_to_string(&config).unwrap(),
        StorageLocationDto::export_to_string(&config).unwrap(),
        LibraryScanStartRequest::export_to_string(&config).unwrap(),
        ScanStartResult::export_to_string(&config).unwrap(),
        ScanCancelResultDto::export_to_string(&config).unwrap(),
        ScanPhase::export_to_string(&config).unwrap(),
        ScanEventData::export_to_string(&config).unwrap(),
        LibraryScanEvent::export_to_string(&config).unwrap(),
        ContinueItemDto::export_to_string(&config).unwrap(),
        ShelfDto::export_to_string(&config).unwrap(),
        HomeDto::export_to_string(&config).unwrap(),
        LibraryShelvesDto::export_to_string(&config).unwrap(),
        ErrorDto::export_to_string(&config).unwrap(),
        LibraryChangedDto::export_to_string(&config).unwrap(),
        FavoriteChangedDto::export_to_string(&config).unwrap(),
        WorkDetailCountsDto::export_to_string(&config).unwrap(),
        WorkDetailHeaderDto::export_to_string(&config).unwrap(),
        WorkGetRequest::export_to_string(&config).unwrap(),
        EditionListByWorkRequest::export_to_string(&config).unwrap(),
        EditionGetRequest::export_to_string(&config).unwrap(),
        ComicChapterAvailabilityDto::export_to_string(&config).unwrap(),
        ComicEditionFacetKindDto::export_to_string(&config).unwrap(),
        ComicScanGroupKindDto::export_to_string(&config).unwrap(),
        ComicColorModeDto::export_to_string(&config).unwrap(),
        ComicEditionProfileDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogItemDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogGetRequest::export_to_string(&config).unwrap(),
        ComicChapterCatalogDto::export_to_string(&config).unwrap(),
        ComicChapterSourceStatusDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogRefreshStateDto::export_to_string(&config).unwrap(),
        ComicRegisteredChapterCatalogItemDto::export_to_string(&config).unwrap(),
        ComicRegisteredChapterCatalogDto::export_to_string(&config).unwrap(),
        ComicWorkChapterCatalogRequestDto::export_to_string(&config).unwrap(),
        ComicChapterAggregateStatusDto::export_to_string(&config).unwrap(),
        ComicWorkEditionDto::export_to_string(&config).unwrap(),
        ComicChapterSourceSummaryDto::export_to_string(&config).unwrap(),
        ComicWorkChapterDto::export_to_string(&config).unwrap(),
        ComicCatalogRefreshOutcomeStatusDto::export_to_string(&config).unwrap(),
        ComicCatalogRefreshReceiptDto::export_to_string(&config).unwrap(),
        ComicWorkCatalogStatusDto::export_to_string(&config).unwrap(),
        ComicWorkChapterCatalogDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidatesGetRequestDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidateDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidatesDto::export_to_string(&config).unwrap(),
        ComicChapterSourceIdentityDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRequestDto::export_to_string(&config).unwrap(),
        ComicPageProgressRemapRequestDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationStatusDto::export_to_string(&config).unwrap(),
        ComicChapterMatchKindDto::export_to_string(&config).unwrap(),
        ComicMatchConfidenceDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationModeDto::export_to_string(&config).unwrap(),
        ComicChapterEvidenceKindDto::export_to_string(&config).unwrap(),
        ComicChapterEvidenceDto::export_to_string(&config).unwrap(),
        ComicChapterMatchDto::export_to_string(&config).unwrap(),
        ComicPageMappingConfidenceDto::export_to_string(&config).unwrap(),
        ComicPageMappingStrategyDto::export_to_string(&config).unwrap(),
        ComicPageMigrationDto::export_to_string(&config).unwrap(),
        ComicProgressSnapshotDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationReceiptDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationResultDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRevertRequestDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRevertResultDto::export_to_string(&config).unwrap(),
        EditionAvailabilityDto::export_to_string(&config).unwrap(),
        EditionSummaryDto::export_to_string(&config).unwrap(),
        EditionDetailDto::export_to_string(&config).unwrap(),
        MediaItemStatusDto::export_to_string(&config).unwrap(),
        MediaItemSummaryDto::export_to_string(&config).unwrap(),
        ResourceTypeDto::export_to_string(&config).unwrap(),
        AvailabilityDto::export_to_string(&config).unwrap(),
        ResourceSummaryDto::export_to_string(&config).unwrap(),
        ResourceListByMediaItemRequest::export_to_string(&config).unwrap(),
        ResourceListDto::export_to_string(&config).unwrap(),
        DownloadStateDto::export_to_string(&config).unwrap(),
        DownloadTaskDto::export_to_string(&config).unwrap(),
        DownloadCreateRequest::export_to_string(&config).unwrap(),
        DownloadListRequest::export_to_string(&config).unwrap(),
        DownloadTaskActionRequest::export_to_string(&config).unwrap(),
        DownloadMutationResultDto::export_to_string(&config).unwrap(),
        DownloadRevealResultDto::export_to_string(&config).unwrap(),
        DownloadEventKind::export_to_string(&config).unwrap(),
        DownloadEventData::export_to_string(&config).unwrap(),
        DownloadEvent::export_to_string(&config).unwrap(),
        // v0.2 契约冻结（契约 §36；CONTRACT-V02-*）
        ExternalIdProviderDto::export_to_string(&config).unwrap(),
        ExternalIdDto::export_to_string(&config).unwrap(),
        SourceCategoryDto::export_to_string(&config).unwrap(),
        SourceModeDto::export_to_string(&config).unwrap(),
        SourceKindDto::export_to_string(&config).unwrap(),
        SourceHealthDto::export_to_string(&config).unwrap(),
        SourceDescriptorDto::export_to_string(&config).unwrap(),
        SourceRegistryDto::export_to_string(&config).unwrap(),
        SourceRegistrySetRequest::export_to_string(&config).unwrap(),
        SourceRegistrySetResult::export_to_string(&config).unwrap(),
        SourceEndpointSetRequest::export_to_string(&config).unwrap(),
        SourceEndpointSetResult::export_to_string(&config).unwrap(),
        SourceAddRequest::export_to_string(&config).unwrap(),
        SourceAddResult::export_to_string(&config).unwrap(),
        SourceUpdateRequest::export_to_string(&config).unwrap(),
        SourceUpdateResult::export_to_string(&config).unwrap(),
        SourceRemoveRequest::export_to_string(&config).unwrap(),
        SourceRemoveResult::export_to_string(&config).unwrap(),
        SourceSetCredentialRequest::export_to_string(&config).unwrap(),
        SourceWorkImportRequest::export_to_string(&config).unwrap(),
        SourceWorkImportResult::export_to_string(&config).unwrap(),
        SearchSourceStartRequest::export_to_string(&config).unwrap(),
        SearchStartResultDto::export_to_string(&config).unwrap(),
        SearchSourceEventKind::export_to_string(&config).unwrap(),
        SearchSourceEventData::export_to_string(&config).unwrap(),
        SearchSourceEvent::export_to_string(&config).unwrap(),
        SearchSourceCancelRequest::export_to_string(&config).unwrap(),
        SearchSourceCancelResultDto::export_to_string(&config).unwrap(),
        StreamKindDto::export_to_string(&config).unwrap(),
        CredentialProviderDto::export_to_string(&config).unwrap(),
        CredentialStatusRequest::export_to_string(&config).unwrap(),
        CredentialStatusDto::export_to_string(&config).unwrap(),
        CredentialSetRequest::export_to_string(&config).unwrap(),
        CredentialDeleteRequest::export_to_string(&config).unwrap(),
        LocatorKindDto::export_to_string(&config).unwrap(),
        MediaStateGetRequest::export_to_string(&config).unwrap(),
        MediaStateProgressDto::export_to_string(&config).unwrap(),
        HistorySummaryDto::export_to_string(&config).unwrap(),
        MediaStateDto::export_to_string(&config).unwrap(),
        EnrichmentStatusWire::export_to_string(&config).unwrap(),
        EnrichmentStatusRequest::export_to_string(&config).unwrap(),
        EnrichmentStateDto::export_to_string(&config).unwrap(),
        MetadataChangedDto::export_to_string(&config).unwrap(),
        TrendingItemDto::export_to_string(&config).unwrap(),
        TrendingBoardDto::export_to_string(&config).unwrap(),
        TrendingBoardsDto::export_to_string(&config).unwrap(),
        AppDirectoryKindDto::export_to_string(&config).unwrap(),
        AppDirectoryDto::export_to_string(&config).unwrap(),
        ThirdPartyNoticeDto::export_to_string(&config).unwrap(),
        AppInfoDto::export_to_string(&config).unwrap(),
        ErrorReportLevelDto::export_to_string(&config).unwrap(),
        ErrorReportRedactionStatusDto::export_to_string(&config).unwrap(),
        ErrorReportRedactionDto::export_to_string(&config).unwrap(),
        ErrorReportDetailsDto::export_to_string(&config).unwrap(),
        ErrorReportPreviewDto::export_to_string(&config).unwrap(),
        ErrorReportPreviewRequest::export_to_string(&config).unwrap(),
        ErrorReportConfirmRequest::export_to_string(&config).unwrap(),
        ErrorReportConfirmResultDto::export_to_string(&config).unwrap(),
        ErrorReportActionStatusDto::export_to_string(&config).unwrap(),
        ErrorReportActionResultDto::export_to_string(&config).unwrap(),
        ErrorReportActionRequest::export_to_string(&config).unwrap(),
        CacheScopeDto::export_to_string(&config).unwrap(),
        CacheClearResultDto::export_to_string(&config).unwrap(),
        VideoScreenshotBeginResultDto::export_to_string(&config).unwrap(),
        VideoScreenshotChunkRequest::export_to_string(&config).unwrap(),
        VideoScreenshotStatusDto::export_to_string(&config).unwrap(),
        VideoScreenshotResultDto::export_to_string(&config).unwrap(),
        CastProtocolDto::export_to_string(&config).unwrap(),
        CastDeviceDto::export_to_string(&config).unwrap(),
        CastDiscoverRequest::export_to_string(&config).unwrap(),
        CastDiscoverResult::export_to_string(&config).unwrap(),
        CastPlayRequest::export_to_string(&config).unwrap(),
        CastPlayResult::export_to_string(&config).unwrap(),
        CastTransportStateDto::export_to_string(&config).unwrap(),
        CastStatusRequest::export_to_string(&config).unwrap(),
        CastStatusDto::export_to_string(&config).unwrap(),
        CastStopRequest::export_to_string(&config).unwrap(),
        CastStopResult::export_to_string(&config).unwrap(),
        // 阅读（契约 §19.1）
        ReaderTocGetRequest::export_to_string(&config).unwrap(),
        TocItemDto::export_to_string(&config).unwrap(),
        ReaderTocResultDto::export_to_string(&config).unwrap(),
        ReaderSearchRequest::export_to_string(&config).unwrap(),
        ReaderSearchHitDto::export_to_string(&config).unwrap(),
        ReaderSearchResultDto::export_to_string(&config).unwrap(),
        ReaderSearchEventKind::export_to_string(&config).unwrap(),
        ReaderSearchEventData::export_to_string(&config).unwrap(),
        ReaderSearchEvent::export_to_string(&config).unwrap(),
        ReaderSearchCancelRequest::export_to_string(&config).unwrap(),
        ReaderSearchCancelResultDto::export_to_string(&config).unwrap(),
        // 资源内设（ADR-RESOURCE-PREF-001）
        PreferenceTargetDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontFamilyDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontSizeDto::export_to_string(&config).unwrap(),
        PreferenceReadingLineHeightDto::export_to_string(&config).unwrap(),
        PreferenceReadingContentWidthDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontWeightDto::export_to_string(&config).unwrap(),
        PreferenceReadingLetterSpacingDto::export_to_string(&config).unwrap(),
        PreferenceReadingThemeDto::export_to_string(&config).unwrap(),
        PreferenceReadingPaginationDto::export_to_string(&config).unwrap(),
        PreferenceComicViewModeDto::export_to_string(&config).unwrap(),
        PreferenceComicDirectionDto::export_to_string(&config).unwrap(),
        PreferenceComicPageGapDto::export_to_string(&config).unwrap(),
        PreferenceComicPreloadPagesDto::export_to_string(&config).unwrap(),
        PreferenceReadingPatchDto::export_to_string(&config).unwrap(),
        PreferenceComicPatchDto::export_to_string(&config).unwrap(),
        PreferenceReadingSettingsDto::export_to_string(&config).unwrap(),
        PreferenceComicSettingsDto::export_to_string(&config).unwrap(),
        PreferenceGetRequest::export_to_string(&config).unwrap(),
        PreferenceUpdateRequest::export_to_string(&config).unwrap(),
        PreferenceGetResult::export_to_string(&config).unwrap(),
        PreferenceUpdateResult::export_to_string(&config).unwrap(),
        // 报刊层级只读查询（契约 §12 `ContentCategory::Periodical`）
        PeriodicalTreeGetRequest::export_to_string(&config).unwrap(),
        PageRangeDto::export_to_string(&config).unwrap(),
        PeriodicalArticleAvailabilityDto::export_to_string(&config).unwrap(),
        PeriodicalDto::export_to_string(&config).unwrap(),
        PeriodicalArticleDto::export_to_string(&config).unwrap(),
        PeriodicalIssueDto::export_to_string(&config).unwrap(),
        PeriodicalVolumeDto::export_to_string(&config).unwrap(),
        PeriodicalTreeDto::export_to_string(&config).unwrap(),
        AgentSettingsSectionDto::export_to_string(&config).unwrap(),
        AgentSettingsRedactedFieldDto::export_to_string(&config).unwrap(),
        AgentCapabilitySetDto::export_to_string(&config).unwrap(),
        AgentCapabilityManifestDto::export_to_string(&config).unwrap(),
        AgentSettingsSubjectDto::export_to_string(&config).unwrap(),
        AgentSettingsReadingSnapshotDto::export_to_string(&config).unwrap(),
        AgentSettingsContextDto::export_to_string(&config).unwrap(),
        AgentSettingsProposalCreateRequest::export_to_string(&config).unwrap(),
        AgentSettingsProposalStatusDto::export_to_string(&config).unwrap(),
        AgentSettingChangeDto::export_to_string(&config).unwrap(),
        AgentSettingsProposalDto::export_to_string(&config).unwrap(),
        AgentSettingChangeReceiptDto::export_to_string(&config).unwrap(),
        AgentSettingsProposalApproveRequest::export_to_string(&config).unwrap(),
        AgentSettingsProposalRejectRequest::export_to_string(&config).unwrap(),
        AgentSettingsProposalGetRequest::export_to_string(&config).unwrap(),
        AgentSettingChangeReceiptGetRequest::export_to_string(&config).unwrap(),
        AgentSettingsProposalApproveResultDto::export_to_string(&config).unwrap(),
        AgentSettingsProposalRejectResultDto::export_to_string(&config).unwrap(),
        AgentSettingsProposalGetResultDto::export_to_string(&config).unwrap(),
        // 应用外观（Appearance；契约 §12、045/046）
        AppearanceAssetKindDto::export_to_string(&config).unwrap(),
        AppearanceAssetValidationStateDto::export_to_string(&config).unwrap(),
        AppearanceAssetDto::export_to_string(&config).unwrap(),
        AppearanceAssetsListRequest::export_to_string(&config).unwrap(),
        AppearanceAssetsDto::export_to_string(&config).unwrap(),
        AppearanceAssetImportRequest::export_to_string(&config).unwrap(),
        AppearanceAssetDeleteRequest::export_to_string(&config).unwrap(),
        AppearanceAssetDeleteResultDto::export_to_string(&config).unwrap(),
        HomeModuleIdDto::export_to_string(&config).unwrap(),
        HomeModuleSizeDto::export_to_string(&config).unwrap(),
        HomeModulePlacementDto::export_to_string(&config).unwrap(),
        HomeLayoutDto::export_to_string(&config).unwrap(),
        HomeLayoutSnapshotDto::export_to_string(&config).unwrap(),
        HomeLayoutSaveRequest::export_to_string(&config).unwrap(),
        HomeLayoutResetRequest::export_to_string(&config).unwrap(),
        HomeLayoutMutationResultDto::export_to_string(&config).unwrap(),
        // 设置页总览布局（048）：与首页布局平行的第二套网格事实
        OverviewModuleIdDto::export_to_string(&config).unwrap(),
        OverviewModuleSizeDto::export_to_string(&config).unwrap(),
        OverviewModulePlacementDto::export_to_string(&config).unwrap(),
        OverviewLayoutDto::export_to_string(&config).unwrap(),
        OverviewLayoutSnapshotDto::export_to_string(&config).unwrap(),
        OverviewLayoutSaveRequest::export_to_string(&config).unwrap(),
        OverviewLayoutResetRequest::export_to_string(&config).unwrap(),
        OverviewLayoutMutationResultDto::export_to_string(&config).unwrap(),
        // 阅读总览（Reading Overview；契约 §12）
        ReadingSessionCategoryDto::export_to_string(&config).unwrap(),
        ReadingOverviewGetRequest::export_to_string(&config).unwrap(),
        ReadingOverviewRangeDto::export_to_string(&config).unwrap(),
        ReadingDailyBucketDto::export_to_string(&config).unwrap(),
        ReadingCategoryTotalDto::export_to_string(&config).unwrap(),
        ReadingHeatmapCellDto::export_to_string(&config).unwrap(),
        ReadingOverviewDto::export_to_string(&config).unwrap(),
        AgentBrokerStatusDto::export_to_string(&config).unwrap(),
        AgentBrokerStatusResultDto::export_to_string(&config).unwrap(),
        // Agent 只读投影：设置来源分层 / 资源偏好 / 书库摘要 / 媒体声明式能力 / 引导状态
        // （与设置提案走同一条 Proposal → UI approval → CAS 路径，这里只有只读事实）
        AgentSettingSourceLayerDto::export_to_string(&config).unwrap(),
        AgentSettingSourceDto::export_to_string(&config).unwrap(),
        AgentSettingSourcesDto::export_to_string(&config).unwrap(),
        AgentResourcePreferenceScopeDto::export_to_string(&config).unwrap(),
        AgentResourcePreferenceSnapshotDto::export_to_string(&config).unwrap(),
        AgentResourcePreferencePatchDto::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalCreateRequest::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalDto::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalGetRequest::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalGetResultDto::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalApproveRequest::export_to_string(&config).unwrap(),
        AgentResourcePreferenceProposalApproveResultDto::export_to_string(&config).unwrap(),
        AgentLibrarySummaryCountsDto::export_to_string(&config).unwrap(),
        AgentLibraryCategoryCountDto::export_to_string(&config).unwrap(),
        AgentLibraryRecentItemDto::export_to_string(&config).unwrap(),
        AgentLibrarySummaryDto::export_to_string(&config).unwrap(),
        AgentMediaAvailabilityDto::export_to_string(&config).unwrap(),
        AgentMediaCapabilityFlagDto::export_to_string(&config).unwrap(),
        AgentMediaCapabilityDto::export_to_string(&config).unwrap(),
        AgentMediaCapabilitiesDto::export_to_string(&config).unwrap(),
        AgentOnboardingStateDto::export_to_string(&config).unwrap(),
        // AI Provider Profile 基础切片（docs/architecture/AI_SYSTEM.md）
        AiProviderKindDto::export_to_string(&config).unwrap(),
        AiModelCapabilityDto::export_to_string(&config).unwrap(),
        AiProviderProfileDto::export_to_string(&config).unwrap(),
        AiProviderProfileListResultDto::export_to_string(&config).unwrap(),
        AiProviderProfileGetRequest::export_to_string(&config).unwrap(),
        AiProviderProfileUpsertRequest::export_to_string(&config).unwrap(),
        AiProviderProfileDeleteRequest::export_to_string(&config).unwrap(),
        AiProviderProfileDeleteResultDto::export_to_string(&config).unwrap(),
        AiProviderModelsListRequest::export_to_string(&config).unwrap(),
        AiProviderModelsCatalogStateDto::export_to_string(&config).unwrap(),
        AiProviderModelDto::export_to_string(&config).unwrap(),
        AiProviderModelsCatalogDto::export_to_string(&config).unwrap(),
        AiSettingsRecommendationGenerateRequest::export_to_string(&config).unwrap(),
        AiSettingsRecommendationDto::export_to_string(&config).unwrap(),
        AgentTraceEventKindDto::export_to_string(&config).unwrap(),
        AgentTraceGetRequest::export_to_string(&config).unwrap(),
        AgentTraceEventDto::export_to_string(&config).unwrap(),
        AgentTraceGetResultDto::export_to_string(&config).unwrap(),
        // TVBox / FongMi 配置预览（Film/TV Provider 基础切片）
        TvboxConfigImplementationKindDto::export_to_string(&config).unwrap(),
        TvboxConfigPreviewRequest::export_to_string(&config).unwrap(),
        TvboxConfigPreviewDto::export_to_string(&config).unwrap(),
        TvboxConfigSaveRequest::export_to_string(&config).unwrap(),
        TvboxConfigSaveResult::export_to_string(&config).unwrap(),
        CloudConnectStatusDto::export_to_string(&config).unwrap(),
        CloudAccountDto::export_to_string(&config).unwrap(),
        CloudConnectAttemptDto::export_to_string(&config).unwrap(),
        CloudConnectPollDto::export_to_string(&config).unwrap(),
        CloudFolderDto::export_to_string(&config).unwrap(),
        CloudBrowseEntryDto::export_to_string(&config).unwrap(),
        CloudBrowsePageDto::export_to_string(&config).unwrap(),
        CloudObjectDto::export_to_string(&config).unwrap(),
        CloudStorageListDto::export_to_string(&config).unwrap(),
        CloudConnectBeginRequest::export_to_string(&config).unwrap(),
        CloudAccountDisconnectRequest::export_to_string(&config).unwrap(),
        CloudRegisterFolderRequest::export_to_string(&config).unwrap(),
        CloudImportPdfRequest::export_to_string(&config).unwrap(),
    ] {
        for line in declaration.lines() {
            if line.trim_start().starts_with("import type") {
                continue;
            }
            out.push_str(line.trim_end());
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_output_contains_all_expected_types() {
        let out = generate_wire_bindings();
        for expected in [
            "ContentCategory",
            "CompletionWire",
            "WorkCardDto",
            "PageDto",
            "ProgressSaveRequest",
            "ProgressMarkCompletedRequest",
            "HistoryEntryDto",
            "SearchHistoryEntryDto",
            "SearchHistoryListRequest",
            "MarkerDto",
            "StorageLocationDto",
            "ScanCancelResultDto",
            "LibraryScanEvent",
            "HomeDto",
            "ShelfDto",
            "WorkDetailHeaderDto",
            "WorkGetRequest",
            "ResourceSummaryDto",
            "ComicPageManifestDto",
            "ComicWorkChapterCatalogRequestDto",
            "ComicChapterAggregateStatusDto",
            "ComicWorkEditionDto",
            "ComicChapterSourceSummaryDto",
            "ComicWorkChapterDto",
            "ComicCatalogRefreshOutcomeStatusDto",
            "ComicCatalogRefreshReceiptDto",
            "ComicWorkCatalogStatusDto",
            "ComicWorkChapterCatalogDto",
            "ComicProgressSnapshotDto",
            "ComicProgressMigrationReceiptDto",
            "DownloadTaskDto",
            "DownloadCreateRequest",
            "DownloadMutationResultDto",
            "DownloadRevealResultDto",
            "CacheScopeDto",
            "CacheClearResultDto",
            "ErrorReportLevelDto",
            "ErrorReportPreviewDto",
            "ErrorReportPreviewRequest",
            "ErrorReportConfirmResultDto",
            "ErrorReportActionResultDto",
            "VideoScreenshotBeginResultDto",
            "VideoScreenshotChunkRequest",
            "VideoScreenshotStatusDto",
            "VideoScreenshotResultDto",
            "ReaderTocGetRequest",
            "TocItemDto",
            "ReaderTocResultDto",
            "ReaderSearchRequest",
            "ReaderSearchHitDto",
            "ReaderSearchResultDto",
            "ReaderSearchEventKind",
            "ReaderSearchEventData",
            "ReaderSearchEvent",
            "ReaderSearchCancelRequest",
            "ReaderSearchCancelResultDto",
            "SubtitleFormatDto",
            "SubtitleTrackDto",
            "PreferenceTargetDto",
            "PreferenceReadingPatchDto",
            "PreferenceComicPatchDto",
            "PreferenceReadingSettingsDto",
            "PreferenceComicSettingsDto",
            "PreferenceGetRequest",
            "PreferenceUpdateRequest",
            "PreferenceGetResult",
            "PreferenceUpdateResult",
            "PeriodicalTreeGetRequest",
            "PageRangeDto",
            "PeriodicalArticleAvailabilityDto",
            "PeriodicalDto",
            "PeriodicalArticleDto",
            "PeriodicalIssueDto",
            "PeriodicalVolumeDto",
            "PeriodicalTreeDto",
            "AppearanceAssetKindDto",
            "AppearanceAssetValidationStateDto",
            "AppearanceAssetDto",
            "AppearanceAssetsListRequest",
            "AppearanceAssetsDto",
            "AppearanceAssetImportRequest",
            "AppearanceAssetDeleteRequest",
            "AppearanceAssetDeleteResultDto",
            "HomeModuleIdDto",
            "HomeModuleSizeDto",
            "HomeModulePlacementDto",
            "HomeLayoutDto",
            "HomeLayoutSnapshotDto",
            "HomeLayoutSaveRequest",
            "HomeLayoutResetRequest",
            "HomeLayoutMutationResultDto",
            "OverviewModuleIdDto",
            "OverviewModuleSizeDto",
            "OverviewModulePlacementDto",
            "OverviewLayoutDto",
            "OverviewLayoutSnapshotDto",
            "OverviewLayoutSaveRequest",
            "OverviewLayoutResetRequest",
            "OverviewLayoutMutationResultDto",
            "ReadingSessionCategoryDto",
            "ReadingOverviewGetRequest",
            "ReadingOverviewRangeDto",
            "ReadingDailyBucketDto",
            "ReadingCategoryTotalDto",
            "ReadingHeatmapCellDto",
            "ReadingOverviewDto",
            "AgentSettingSourceLayerDto",
            "AgentSettingSourceDto",
            "AgentSettingSourcesDto",
            "AgentResourcePreferenceScopeDto",
            "AgentResourcePreferenceSnapshotDto",
            "AgentResourcePreferencePatchDto",
            "AgentResourcePreferenceProposalCreateRequest",
            "AgentResourcePreferenceProposalDto",
            "AgentResourcePreferenceProposalGetRequest",
            "AgentResourcePreferenceProposalGetResultDto",
            "AgentResourcePreferenceProposalApproveRequest",
            "AgentResourcePreferenceProposalApproveResultDto",
            "AgentLibrarySummaryCountsDto",
            "AgentLibraryCategoryCountDto",
            "AgentLibraryRecentItemDto",
            "AgentLibrarySummaryDto",
            "AgentMediaAvailabilityDto",
            "AgentMediaCapabilityFlagDto",
            "AgentMediaCapabilityDto",
            "AgentMediaCapabilitiesDto",
            "AgentOnboardingStateDto",
            "CloudConnectStatusDto",
            "CloudAccountDto",
            "CloudConnectAttemptDto",
            "CloudConnectPollDto",
            "CloudFolderDto",
            "CloudBrowseEntryDto",
            "CloudBrowsePageDto",
            "CloudObjectDto",
            "CloudStorageListDto",
            "CloudConnectBeginRequest",
            "CloudAccountDisconnectRequest",
            "CloudRegisterFolderRequest",
            "CloudImportPdfRequest",
        ] {
            assert!(out.contains(expected), "生成物缺少类型 {expected}");
        }
        assert!(
            !out.contains("import type"),
            "单文件生成不得含跨文件 import"
        );
        assert!(
            out.lines().all(|line| line == line.trim_end()),
            "checked-in wire.ts 不得含行尾空白"
        );
        assert!(out.contains("positionMs: number"), "u64 wire 必须是 number");
        assert!(
            out.contains("schemaVersion: 1"),
            "WorkDetailHeaderDto schemaVersion 必须是 literal 1"
        );
    }

    #[test]
    fn page_dto_uses_null_not_required_number() {
        let out = generate_wire_bindings();
        assert!(
            out.contains("total: number | null"),
            "PageDto.total 必须是 number | null"
        );
        assert!(
            out.contains("schemaVersion"),
            "PageDto 必须带 schemaVersion"
        );
    }

    #[test]
    fn ai_provider_wire_shape_is_frozen() {
        let out = generate_wire_bindings();
        for expected in [
            "AiProviderKindDto",
            "AiModelCapabilityDto",
            "AiProviderProfileDto",
            "AiProviderProfileListResultDto",
            "AiProviderProfileGetRequest",
            "AiProviderProfileUpsertRequest",
            "AiProviderProfileDeleteRequest",
            "AiProviderProfileDeleteResultDto",
            "AiProviderModelsListRequest",
            "AiProviderModelsCatalogStateDto",
            "AiProviderModelDto",
            "AiProviderModelsCatalogDto",
            "AiSettingsRecommendationGenerateRequest",
            "AiSettingsRecommendationDto",
            "AgentTraceEventKindDto",
            "AgentTraceGetRequest",
            "AgentTraceEventDto",
            "AgentTraceGetResultDto",
        ] {
            assert!(out.contains(expected), "生成物缺少类型 {expected}");
        }
        // 种类字符串必须与领域/数据库一致（`rename_all = snake_case` 会拆成
        // `open_ai_compatible`，那是错误的稳定值）。
        assert!(
            out.contains("export type AiProviderKindDto = \"openai_compatible\";"),
            "AiProviderKindDto 必须序列化为 openai_compatible"
        );
        assert!(
            !out.contains("open_ai_compatible"),
            "不得出现被 snake_case 拆开的种类值"
        );
        // 能力三态必须完整；缺一态就会让 UI 把「没声明」读成「支持」或「不支持」。
        assert!(out.contains(
            "export type AiModelCapabilityDto = \"supported\" | \"unsupported\" | \"unknown\";"
        ));
        // `created` 是 Unix 秒，wire 上是 number 而不是 bigint。
        assert!(
            out.contains("created: number | null"),
            "AiProviderModelDto.created 必须是 number | null"
        );
        // 凭据 Provider 必须包含 ai 命名空间。
        assert!(
            out.contains("export type CredentialProviderDto = \"webdav\" | \"opds\" | \"ai\";")
        );
        // secret 绝不能出现在任何 AI Provider 线上类型里。
        for forbidden in ["apiKey", "api_key", "secret", "credentialRef", "target"] {
            for line in out
                .lines()
                .filter(|line| line.contains("AiProvider") || line.contains("AiModel"))
            {
                assert!(
                    !line.contains(forbidden),
                    "AI wire 类型不得包含 {forbidden}: {line}"
                );
            }
        }
    }

    #[test]
    fn ai_provider_profile_dto_serializes_without_credential_material() {
        let dto = AiProviderProfileDto {
            schema_version: 1,
            profile_id: "gw".into(),
            display_name: "自建网关".into(),
            kind: AiProviderKindDto::OpenAiCompatible,
            endpoint: "https://gateway.example.invalid/v1".into(),
            enabled: true,
            selected_model_id: None,
            credential_configured: true,
            revision: "rev-1".into(),
            created_at: "2026-09-18T00:00:00Z".into(),
            updated_at: "2026-09-18T00:00:00Z".into(),
        };
        let encoded = serde_json::to_string(&dto).unwrap();
        assert!(encoded.contains("\"kind\":\"openai_compatible\""));
        for forbidden in ["secret", "haven:ai:", "credentialRef", "apiKey"] {
            assert!(
                !encoded.contains(forbidden),
                "不得包含 {forbidden}: {encoded}"
            );
        }
    }

    #[test]
    fn agent_read_only_projection_shape_is_frozen() {
        let out = generate_wire_bindings();
        // 只截取本次新增的只读投影块（从设置来源分层到 AI Provider 之前），
        // 这样"不得出现 secret/路径字段"的断言不会被别处的合法字段干扰。
        let start = out
            .find("export type AgentSettingSourceLayerDto")
            .expect("生成物缺少 Agent 只读投影块");
        let end = out
            .find("export type AiProviderKindDto")
            .expect("生成物缺少 AI Provider 块");
        let block = &out[start..end];

        // 闭合枚举值：设置来源层与媒体可用性都必须是稳定的小写 token。
        assert!(block.contains(
            "export type AgentSettingSourceLayerDto = \"default\" | \"global\" | \"edition\" | \"media_item\";"
        ));
        assert!(block.contains(
            "export type AgentMediaAvailabilityDto = \"available\" | \"unavailable\" | \"unknown\";"
        ));
        assert!(block.contains(
            "export type AgentResourcePreferenceScopeDto = \"edition\" | \"media_item\";"
        ));
        // wire 的 canonical 分类没有 `all`：无法归类的最近作品必须是 null，
        // 不能让页面把它读成某个具体分类。
        assert!(
            block.contains("ContentCategory | null"),
            "无法归类的作品必须投影成 null"
        );
        // 只读投影不得携带凭据、endpoint 或绝对路径字段。
        for forbidden in [
            "apiKey",
            "secret",
            "credential",
            "endpoint",
            "absolutePath",
            "filePath",
        ] {
            assert!(
                !block.contains(forbidden),
                "Agent 只读投影不得包含 {forbidden}"
            );
        }
    }

    /// TVBox / FongMi 配置预览的线上形状必须在两个方向上都被冻住：
    /// 稳定枚举值不能被 snake_case 拆错，响应字段集合也不能被悄悄扩张。
    #[test]
    fn tvbox_config_preview_wire_shape_is_frozen() {
        let out = generate_wire_bindings();
        let start = out
            .find("export type TvboxConfigImplementationKindDto")
            .expect("生成物缺少 TVBox 预览块");
        let block = &out[start..];

        // `JavaScript` 一旦被 rename_all 拆成 `java_script`，这条就会失败。
        assert!(
            block.contains(
                "export type TvboxConfigImplementationKindDto = \"jar\" | \"javascript\" \
                 | \"python\" | \"json_manifest\" | \"unidentified\";"
            ),
            "TVBox 实现种类必须是稳定小写 token"
        );
        assert!(!block.contains("java_script"), "不得出现被拆开的种类值");

        // 请求只带待预览的地址，没有 header、凭据或保存意图。
        assert!(block.contains("export type TvboxConfigPreviewRequest = { url: string, };"));

        let response_start = block
            .find("export type TvboxConfigPreviewDto = ")
            .expect("生成物缺少 TVBox 预览响应");
        // 只扫描这一个类型声明，直到下一个顶层 `export type` 为止；否则下面新增的
        // 保存请求（它**必须**带 url 字段）会被误判成预览响应扩张。
        let response_tail = &block[response_start..];
        let response_end = response_tail[1..]
            .find("\nexport type ")
            .map(|offset| offset + 1)
            .unwrap_or(response_tail.len());
        let response = &response_tail[..response_end];
        for expected in [
            "schemaVersion: 1",
            "siteCount: number",
            "liveCount: number",
            "parserCount: number",
            "skippedSiteRows: number",
            "skippedLiveRows: number",
            "skippedParserRows: number",
            "spiderConfigured: boolean",
            "spiderKind: TvboxConfigImplementationKindDto | null",
            "spiderHasIntegrityDigest: boolean",
            "httpEndpointSiteCount: number",
            "spiderSiteCount: number",
            "unclassifiedSiteCount: number",
            "opaqueTopLevelFieldNames: Array<string>",
            "unrecognizedTopLevelFieldCount: number",
            "withheldTopLevelFieldCount: number",
        ] {
            assert!(response.contains(expected), "预览响应缺少字段 {expected}");
        }

        // 响应里的每个字段名都不得是地址/正文/端点/header/凭据类字段。只扫描字段行
        // 本身，避免文档注释里的说明词造成误判。
        for line in response.lines() {
            let trimmed = line.trim();
            let Some((name, _)) = trimmed.split_once(':') else {
                continue;
            };
            if name.is_empty() || !name.chars().all(|c| c.is_ascii_alphanumeric()) {
                continue;
            }
            for forbidden in [
                "url", "endpoint", "header", "ext", "cookie", "token", "secret", "raw", "json",
                "config",
            ] {
                assert!(
                    !trimmed.contains(forbidden),
                    "预览响应字段不得包含 {forbidden}: {trimmed}"
                );
            }
        }

        // 保存请求只有用户输入（显示名 + 地址）；响应只有 schemaVersion、稳定 sourceId
        // 与同一份预览摘要。地址**必须**留在请求方向，响应里不得出现。
        assert!(
            block.contains(
                "export type TvboxConfigSaveRequest = { displayName: string, url: string, };"
            ),
            "保存请求必须只有 displayName 与 url 两个字段"
        );

        let save_tail = &block[block
            .find("export type TvboxConfigSaveResult = ")
            .expect("生成物缺少 TVBox 保存响应")..];
        let save_end = save_tail[1..]
            .find("\nexport type ")
            .map(|offset| offset + 1)
            .unwrap_or(save_tail.len());
        let save_result = &save_tail[..save_end];
        for expected in [
            "schemaVersion: 1",
            "sourceId: string",
            "preview: TvboxConfigPreviewDto",
        ] {
            assert!(
                save_result.contains(expected),
                "保存响应缺少字段 {expected}"
            );
        }
        for forbidden in ["url", "endpoint", "header", "body", "raw", "config"] {
            assert!(
                !save_result.contains(forbidden),
                "保存响应不得包含 {forbidden}: {save_result}"
            );
        }
    }

    #[test]
    fn download_management_request_exposes_only_task_id() {
        let value = serde_json::to_value(DownloadTaskActionRequest {
            task_id: "task-id".into(),
        })
        .unwrap();
        assert_eq!(value, serde_json::json!({ "taskId": "task-id" }));
    }
}
