//! TypeScript Binding 生成（IPC-WIRE-001 核心：单一事实源、生成物可复现）。
//!
//! `generate_wire_bindings()` 是纯函数：同一 Rust 源码 → 同一 TS 输出。
//! - `examples/gen_wire_bindings.rs` 调用它写盘（`前端/app/src/lib/ipc/generated/wire.ts`）。
//! - 一致性测试（`tests/wire_bindings_consistency.rs`）比对生成结果与 checked-in 文件，
//!   防止生成物漂移（wire.ts 与 Rust 源不一致时测试失败）。

use ts_rs::{Config, TS};

use super::dto::*;

/// 生成完整 wire.ts 内容（不含文件 IO）。
pub fn generate_wire_bindings() -> String {
    let config = Config::default();
    let mut out = String::new();
    out.push_str(
        "// Generated by haven-application/examples/gen_wire_bindings.rs (IPC-WIRE-001)\n",
    );
    out.push_str("// 单一事实源: 后端/crates/haven-application/src/wire/dto.rs — 禁止手改。\n");
    out.push_str("// 契约: plan/FRONTEND_BACKEND_CONTRACT.md §11–§12、§22。\n\n");

    // TypeScript interface 支持前向引用，声明顺序无关紧要。
    // 单文件导出：过滤 ts-rs 为多文件模式生成的 `import type` 行（同文件内类型互相可见）。
    for declaration in [
        ContentCategory::export_to_string(&config).unwrap(),
        QueryCategory::export_to_string(&config).unwrap(),
        MediaTypeDto::export_to_string(&config).unwrap(),
        CompletionWire::export_to_string(&config).unwrap(),
        PrimaryActionKind::export_to_string(&config).unwrap(),
        LabelHint::export_to_string(&config).unwrap(),
        PrimaryActionDto::export_to_string(&config).unwrap(),
        WorkCardDto::export_to_string(&config).unwrap(),
        ProgressSummaryDto::export_to_string(&config).unwrap(),
        LocatorDto::export_to_string(&config).unwrap(),
        VideoLocatorDto::export_to_string(&config).unwrap(),
        BookLocatorDto::export_to_string(&config).unwrap(),
        PdfLocatorDto::export_to_string(&config).unwrap(),
        ComicLocatorDto::export_to_string(&config).unwrap(),
        ArticleLocatorDto::export_to_string(&config).unwrap(),
        TextAnchorDto::export_to_string(&config).unwrap(),
        PageDto::<WorkCardDto>::export_to_string(&config).unwrap(),
        LibraryListSort::export_to_string(&config).unwrap(),
        LibraryListRequest::export_to_string(&config).unwrap(),
        SessionEngineDto::export_to_string(&config).unwrap(),
        SessionOpenRequest::export_to_string(&config).unwrap(),
        SubtitleFormatDto::export_to_string(&config).unwrap(),
        SubtitleTrackDto::export_to_string(&config).unwrap(),
        SessionOpenResultDto::export_to_string(&config).unwrap(),
        SessionCloseRequest::export_to_string(&config).unwrap(),
        SessionCloseResultDto::export_to_string(&config).unwrap(),
        ComicPageManifestGetRequest::export_to_string(&config).unwrap(),
        ComicPageAvailabilityDto::export_to_string(&config).unwrap(),
        ComicPageDto::export_to_string(&config).unwrap(),
        ComicPageManifestDto::export_to_string(&config).unwrap(),
        FavoriteSetRequest::export_to_string(&config).unwrap(),
        FavoriteSetResult::export_to_string(&config).unwrap(),
        ProgressSaveRequest::export_to_string(&config).unwrap(),
        ProgressSaveResult::export_to_string(&config).unwrap(),
        HistoryEntryDto::export_to_string(&config).unwrap(),
        HistoryListRequest::export_to_string(&config).unwrap(),
        SearchHistoryEntryDto::export_to_string(&config).unwrap(),
        SearchHistoryListRequest::export_to_string(&config).unwrap(),
        SearchHistoryRecordRequest::export_to_string(&config).unwrap(),
        SearchHistoryRemoveRequest::export_to_string(&config).unwrap(),
        ProgressRecentRequest::export_to_string(&config).unwrap(),
        ProgressResetRequest::export_to_string(&config).unwrap(),
        MarkerTypeDto::export_to_string(&config).unwrap(),
        MarkerCreateRequest::export_to_string(&config).unwrap(),
        MarkerDto::export_to_string(&config).unwrap(),
        MarkerListRequest::export_to_string(&config).unwrap(),
        MarkerListAllRequest::export_to_string(&config).unwrap(),
        MarkerDeleteRequest::export_to_string(&config).unwrap(),
        StorageProviderTypeDto::export_to_string(&config).unwrap(),
        StorageStatusDto::export_to_string(&config).unwrap(),
        StorageLocationDto::export_to_string(&config).unwrap(),
        LibraryScanStartRequest::export_to_string(&config).unwrap(),
        ScanStartResult::export_to_string(&config).unwrap(),
        ScanCancelResultDto::export_to_string(&config).unwrap(),
        ScanPhase::export_to_string(&config).unwrap(),
        ScanEventData::export_to_string(&config).unwrap(),
        LibraryScanEvent::export_to_string(&config).unwrap(),
        ContinueItemDto::export_to_string(&config).unwrap(),
        ShelfDto::export_to_string(&config).unwrap(),
        HomeDto::export_to_string(&config).unwrap(),
        LibraryShelvesDto::export_to_string(&config).unwrap(),
        ErrorDto::export_to_string(&config).unwrap(),
        LibraryChangedDto::export_to_string(&config).unwrap(),
        FavoriteChangedDto::export_to_string(&config).unwrap(),
        WorkDetailCountsDto::export_to_string(&config).unwrap(),
        WorkDetailHeaderDto::export_to_string(&config).unwrap(),
        WorkGetRequest::export_to_string(&config).unwrap(),
        EditionListByWorkRequest::export_to_string(&config).unwrap(),
        EditionGetRequest::export_to_string(&config).unwrap(),
        ComicChapterAvailabilityDto::export_to_string(&config).unwrap(),
        ComicEditionFacetKindDto::export_to_string(&config).unwrap(),
        ComicScanGroupKindDto::export_to_string(&config).unwrap(),
        ComicColorModeDto::export_to_string(&config).unwrap(),
        ComicEditionProfileDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogItemDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogGetRequest::export_to_string(&config).unwrap(),
        ComicChapterCatalogDto::export_to_string(&config).unwrap(),
        ComicChapterSourceStatusDto::export_to_string(&config).unwrap(),
        ComicChapterCatalogRefreshStateDto::export_to_string(&config).unwrap(),
        ComicRegisteredChapterCatalogItemDto::export_to_string(&config).unwrap(),
        ComicRegisteredChapterCatalogDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidatesGetRequestDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidateDto::export_to_string(&config).unwrap(),
        ComicChapterSourceCandidatesDto::export_to_string(&config).unwrap(),
        ComicChapterSourceIdentityDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRequestDto::export_to_string(&config).unwrap(),
        ComicPageProgressRemapRequestDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationStatusDto::export_to_string(&config).unwrap(),
        ComicChapterMatchKindDto::export_to_string(&config).unwrap(),
        ComicMatchConfidenceDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationModeDto::export_to_string(&config).unwrap(),
        ComicChapterEvidenceKindDto::export_to_string(&config).unwrap(),
        ComicChapterEvidenceDto::export_to_string(&config).unwrap(),
        ComicChapterMatchDto::export_to_string(&config).unwrap(),
        ComicPageMappingConfidenceDto::export_to_string(&config).unwrap(),
        ComicPageMappingStrategyDto::export_to_string(&config).unwrap(),
        ComicPageMigrationDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationResultDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRevertRequestDto::export_to_string(&config).unwrap(),
        ComicProgressMigrationRevertResultDto::export_to_string(&config).unwrap(),
        EditionAvailabilityDto::export_to_string(&config).unwrap(),
        EditionSummaryDto::export_to_string(&config).unwrap(),
        EditionDetailDto::export_to_string(&config).unwrap(),
        MediaItemStatusDto::export_to_string(&config).unwrap(),
        MediaItemSummaryDto::export_to_string(&config).unwrap(),
        ResourceTypeDto::export_to_string(&config).unwrap(),
        AvailabilityDto::export_to_string(&config).unwrap(),
        ResourceSummaryDto::export_to_string(&config).unwrap(),
        ResourceListByMediaItemRequest::export_to_string(&config).unwrap(),
        ResourceListDto::export_to_string(&config).unwrap(),
        DownloadStateDto::export_to_string(&config).unwrap(),
        DownloadTaskDto::export_to_string(&config).unwrap(),
        DownloadCreateRequest::export_to_string(&config).unwrap(),
        DownloadListRequest::export_to_string(&config).unwrap(),
        DownloadTaskActionRequest::export_to_string(&config).unwrap(),
        DownloadMutationResultDto::export_to_string(&config).unwrap(),
        DownloadRevealResultDto::export_to_string(&config).unwrap(),
        DownloadEventKind::export_to_string(&config).unwrap(),
        DownloadEventData::export_to_string(&config).unwrap(),
        DownloadEvent::export_to_string(&config).unwrap(),
        // v0.2 契约冻结（契约 §36；CONTRACT-V02-*）
        ExternalIdProviderDto::export_to_string(&config).unwrap(),
        ExternalIdDto::export_to_string(&config).unwrap(),
        SourceCategoryDto::export_to_string(&config).unwrap(),
        SourceModeDto::export_to_string(&config).unwrap(),
        SourceKindDto::export_to_string(&config).unwrap(),
        SourceHealthDto::export_to_string(&config).unwrap(),
        SourceDescriptorDto::export_to_string(&config).unwrap(),
        SourceRegistryDto::export_to_string(&config).unwrap(),
        SourceRegistrySetRequest::export_to_string(&config).unwrap(),
        SourceRegistrySetResult::export_to_string(&config).unwrap(),
        SourceEndpointSetRequest::export_to_string(&config).unwrap(),
        SourceEndpointSetResult::export_to_string(&config).unwrap(),
        SourceAddRequest::export_to_string(&config).unwrap(),
        SourceAddResult::export_to_string(&config).unwrap(),
        SourceUpdateRequest::export_to_string(&config).unwrap(),
        SourceUpdateResult::export_to_string(&config).unwrap(),
        SourceRemoveRequest::export_to_string(&config).unwrap(),
        SourceRemoveResult::export_to_string(&config).unwrap(),
        SourceSetCredentialRequest::export_to_string(&config).unwrap(),
        SourceWorkImportRequest::export_to_string(&config).unwrap(),
        SourceWorkImportResult::export_to_string(&config).unwrap(),
        SearchSourceStartRequest::export_to_string(&config).unwrap(),
        SearchStartResultDto::export_to_string(&config).unwrap(),
        SearchSourceEventKind::export_to_string(&config).unwrap(),
        SearchSourceEventData::export_to_string(&config).unwrap(),
        SearchSourceEvent::export_to_string(&config).unwrap(),
        SearchSourceCancelRequest::export_to_string(&config).unwrap(),
        SearchSourceCancelResultDto::export_to_string(&config).unwrap(),
        StreamKindDto::export_to_string(&config).unwrap(),
        CredentialProviderDto::export_to_string(&config).unwrap(),
        CredentialStatusRequest::export_to_string(&config).unwrap(),
        CredentialStatusDto::export_to_string(&config).unwrap(),
        CredentialSetRequest::export_to_string(&config).unwrap(),
        CredentialDeleteRequest::export_to_string(&config).unwrap(),
        LocatorKindDto::export_to_string(&config).unwrap(),
        MediaStateGetRequest::export_to_string(&config).unwrap(),
        MediaStateProgressDto::export_to_string(&config).unwrap(),
        HistorySummaryDto::export_to_string(&config).unwrap(),
        MediaStateDto::export_to_string(&config).unwrap(),
        EnrichmentStatusWire::export_to_string(&config).unwrap(),
        EnrichmentStatusRequest::export_to_string(&config).unwrap(),
        EnrichmentStateDto::export_to_string(&config).unwrap(),
        MetadataChangedDto::export_to_string(&config).unwrap(),
        TrendingItemDto::export_to_string(&config).unwrap(),
        TrendingBoardDto::export_to_string(&config).unwrap(),
        TrendingBoardsDto::export_to_string(&config).unwrap(),
        AppDirectoryKindDto::export_to_string(&config).unwrap(),
        AppDirectoryDto::export_to_string(&config).unwrap(),
        ThirdPartyNoticeDto::export_to_string(&config).unwrap(),
        AppInfoDto::export_to_string(&config).unwrap(),
        ErrorReportLevelDto::export_to_string(&config).unwrap(),
        ErrorReportRedactionStatusDto::export_to_string(&config).unwrap(),
        ErrorReportRedactionDto::export_to_string(&config).unwrap(),
        ErrorReportDetailsDto::export_to_string(&config).unwrap(),
        ErrorReportPreviewDto::export_to_string(&config).unwrap(),
        ErrorReportPreviewRequest::export_to_string(&config).unwrap(),
        ErrorReportConfirmRequest::export_to_string(&config).unwrap(),
        ErrorReportConfirmResultDto::export_to_string(&config).unwrap(),
        ErrorReportActionStatusDto::export_to_string(&config).unwrap(),
        ErrorReportActionResultDto::export_to_string(&config).unwrap(),
        ErrorReportActionRequest::export_to_string(&config).unwrap(),
        CacheScopeDto::export_to_string(&config).unwrap(),
        CacheClearResultDto::export_to_string(&config).unwrap(),
        VideoScreenshotBeginResultDto::export_to_string(&config).unwrap(),
        VideoScreenshotChunkRequest::export_to_string(&config).unwrap(),
        VideoScreenshotStatusDto::export_to_string(&config).unwrap(),
        VideoScreenshotResultDto::export_to_string(&config).unwrap(),
        CastProtocolDto::export_to_string(&config).unwrap(),
        CastDeviceDto::export_to_string(&config).unwrap(),
        CastDiscoverRequest::export_to_string(&config).unwrap(),
        CastDiscoverResult::export_to_string(&config).unwrap(),
        CastPlayRequest::export_to_string(&config).unwrap(),
        CastPlayResult::export_to_string(&config).unwrap(),
        CastTransportStateDto::export_to_string(&config).unwrap(),
        CastStatusRequest::export_to_string(&config).unwrap(),
        CastStatusDto::export_to_string(&config).unwrap(),
        CastStopRequest::export_to_string(&config).unwrap(),
        CastStopResult::export_to_string(&config).unwrap(),
        // 阅读（契约 §19.1）
        ReaderTocGetRequest::export_to_string(&config).unwrap(),
        TocItemDto::export_to_string(&config).unwrap(),
        ReaderTocResultDto::export_to_string(&config).unwrap(),
        ReaderSearchRequest::export_to_string(&config).unwrap(),
        ReaderSearchHitDto::export_to_string(&config).unwrap(),
        ReaderSearchResultDto::export_to_string(&config).unwrap(),
        ReaderSearchEventKind::export_to_string(&config).unwrap(),
        ReaderSearchEventData::export_to_string(&config).unwrap(),
        ReaderSearchEvent::export_to_string(&config).unwrap(),
        ReaderSearchCancelRequest::export_to_string(&config).unwrap(),
        ReaderSearchCancelResultDto::export_to_string(&config).unwrap(),
        // 资源内设（ADR-RESOURCE-PREF-001）
        PreferenceTargetDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontFamilyDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontSizeDto::export_to_string(&config).unwrap(),
        PreferenceReadingLineHeightDto::export_to_string(&config).unwrap(),
        PreferenceReadingContentWidthDto::export_to_string(&config).unwrap(),
        PreferenceReadingFontWeightDto::export_to_string(&config).unwrap(),
        PreferenceReadingLetterSpacingDto::export_to_string(&config).unwrap(),
        PreferenceReadingThemeDto::export_to_string(&config).unwrap(),
        PreferenceReadingPaginationDto::export_to_string(&config).unwrap(),
        PreferenceComicViewModeDto::export_to_string(&config).unwrap(),
        PreferenceComicDirectionDto::export_to_string(&config).unwrap(),
        PreferenceComicPageGapDto::export_to_string(&config).unwrap(),
        PreferenceComicPreloadPagesDto::export_to_string(&config).unwrap(),
        PreferenceReadingPatchDto::export_to_string(&config).unwrap(),
        PreferenceComicPatchDto::export_to_string(&config).unwrap(),
        PreferenceReadingSettingsDto::export_to_string(&config).unwrap(),
        PreferenceComicSettingsDto::export_to_string(&config).unwrap(),
        PreferenceGetRequest::export_to_string(&config).unwrap(),
        PreferenceUpdateRequest::export_to_string(&config).unwrap(),
        PreferenceGetResult::export_to_string(&config).unwrap(),
        PreferenceUpdateResult::export_to_string(&config).unwrap(),
    ] {
        for line in declaration.lines() {
            if line.trim_start().starts_with("import type") {
                continue;
            }
            out.push_str(line.trim_end());
            out.push('\n');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_output_contains_all_expected_types() {
        let out = generate_wire_bindings();
        for expected in [
            "ContentCategory",
            "CompletionWire",
            "WorkCardDto",
            "PageDto",
            "ProgressSaveRequest",
            "HistoryEntryDto",
            "SearchHistoryEntryDto",
            "SearchHistoryListRequest",
            "MarkerDto",
            "StorageLocationDto",
            "ScanCancelResultDto",
            "LibraryScanEvent",
            "HomeDto",
            "ShelfDto",
            "WorkDetailHeaderDto",
            "WorkGetRequest",
            "ResourceSummaryDto",
            "ComicPageManifestDto",
            "DownloadTaskDto",
            "DownloadCreateRequest",
            "DownloadMutationResultDto",
            "DownloadRevealResultDto",
            "CacheScopeDto",
            "CacheClearResultDto",
            "ErrorReportLevelDto",
            "ErrorReportPreviewDto",
            "ErrorReportPreviewRequest",
            "ErrorReportConfirmResultDto",
            "ErrorReportActionResultDto",
            "VideoScreenshotBeginResultDto",
            "VideoScreenshotChunkRequest",
            "VideoScreenshotStatusDto",
            "VideoScreenshotResultDto",
            "ReaderTocGetRequest",
            "TocItemDto",
            "ReaderTocResultDto",
            "ReaderSearchRequest",
            "ReaderSearchHitDto",
            "ReaderSearchResultDto",
            "ReaderSearchEventKind",
            "ReaderSearchEventData",
            "ReaderSearchEvent",
            "ReaderSearchCancelRequest",
            "ReaderSearchCancelResultDto",
            "SubtitleFormatDto",
            "SubtitleTrackDto",
            "PreferenceTargetDto",
            "PreferenceReadingPatchDto",
            "PreferenceComicPatchDto",
            "PreferenceReadingSettingsDto",
            "PreferenceComicSettingsDto",
            "PreferenceGetRequest",
            "PreferenceUpdateRequest",
            "PreferenceGetResult",
            "PreferenceUpdateResult",
        ] {
            assert!(out.contains(expected), "生成物缺少类型 {expected}");
        }
        assert!(
            !out.contains("import type"),
            "单文件生成不得含跨文件 import"
        );
        assert!(
            out.lines().all(|line| line == line.trim_end()),
            "checked-in wire.ts 不得含行尾空白"
        );
        assert!(out.contains("positionMs: number"), "u64 wire 必须是 number");
        assert!(
            out.contains("schemaVersion: 1"),
            "WorkDetailHeaderDto schemaVersion 必须是 literal 1"
        );
    }

    #[test]
    fn page_dto_uses_null_not_required_number() {
        let out = generate_wire_bindings();
        assert!(
            out.contains("total: number | null"),
            "PageDto.total 必须是 number | null"
        );
        assert!(
            out.contains("schemaVersion"),
            "PageDto 必须带 schemaVersion"
        );
    }

    #[test]
    fn download_management_request_exposes_only_task_id() {
        let value = serde_json::to_value(DownloadTaskActionRequest {
            task_id: "task-id".into(),
        })
        .unwrap();
        assert_eq!(value, serde_json::json!({ "taskId": "task-id" }));
    }
}
